### ISSUE TITLE
Pull quotes formatting

### ISSUE THREAD

**Issue by yatil** [w3c/wai-website#101]
**Styling:**

- [x] Font weight
- [x] Font size
- [x] Alignment options (float left/right)
- [x] Color options
- [x] Add to theme

rel: https://github.com/w3c/wai-bcase/issues/28

**Comment by slhenry** [comment]
Important: Not all quotes will be this big. For example, we don't want the quote at https://www.w3.org/WAI/fundamentals/accessibility-intro/#context to stand out so much.

Color: Think it would be better if the big quote mark is the same color as the text.

Bolding: I think the name, title, organization should all be the same - either all bold or none bold. Rationale: Mixing bold and not bold adds a little visual complexity. Also, I think in many cases the title and/or organization is actually more important than the name.

Note: Generally italics are harder to read and should be avoided for lots of text. However, in this font, I find the italics OK legibility. So I'm OK with italics for quotes.

**Comment by yatil** [comment]
- Removed <strong> around names.
- The color of the quote mark adjusted.
- Added another color variant.
