### ISSUE TITLE
Link is this post is broken to "Web Accessibility Perspectives"

### ISSUE THREAD

**Issue by idonahue** [w3c/wai-website#1022]
### Resource URL

https://www.w3.org/WAI/news/2016-05-17/new-videos-perspectives-on-web-accessibility-essential-for-some-useful-for-all/

### Description

I google searched "" and the top result was this post. It linked to resources, but the resource link went to the wrong place. I looked at the post template and it seems to be working but the `relative` link must have a `/` at the end which is giving the generated URL to end with `//` and gives a `400` error. 

Image link and text link are broken for "Web Accessibility Perspectives"

Goes to : `https://www.w3.org/WAI/perspective-videos//`. 
There is an extra `/` at the end that should be removed. 

![CleanShot 2024-12-18 at 12 15 01@2x](https://github.com/user-attachments/assets/5b7e64a1-b123-446f-b4c3-d13e0d373393)

**Post template**
![CleanShot 2024-12-18 at 12 23 06@2x](https://github.com/user-attachments/assets/9846c540-ffe2-4499-8dc2-2df0108dc770)

**Google search result**
![CleanShot 2024-12-18 at 12 21 08@2x](https://github.com/user-attachments/assets/6a4cff54-364e-46e3-91c1-65add246b549)

### Resource Shortname

wai-news

**Comment by remibetin** [comment]
Thanks @idonahue We have fixed the issue: https://www.w3.org/WAI/news/2016-05-17/new-videos-perspectives-on-web-accessibility-essential-for-some-useful-for-all/
