### ISSUE TITLE
Update translation status

### ISSUE THREAD

**Issue by codersjj** [w3c/wai-website#1025]
### Resource URL

https://www.w3.org/WAI/about/translating/sitemaps/sitemap-zh-hans/

### Description

Can I update the `Translation Status` in the `Priorities Status` section? 😃 If yes, could someone tell me which file to edit on GitHub? I found [this file](https://github.com/w3c/wai-website/edit/main/collections/_translations-sitemaps/sitemap-zh-hans.md), but it doesn’t seem to contain the corresponding content. 😕

**Comment by remibetin** [comment]
> Can I update the Translation Status in the Priorities Status section?

@codersjj Status are automatically updated and are based on the published translations. "Up-to-date", "Translation needs update" and "No translation" are the only available statuses.

The ongoing translation work is tracked in [WAI Translations GitHub project](https://github.com/orgs/w3c/projects/46)

**Comment by codersjj** [comment]
> > Can I update the Translation Status in the Priorities Status section?
> 
> @codersjj Status are automatically updated and are based on the published translations. "Up-to-date", "Translation needs update" and "No translation" are the only available statuses.
> 
> The ongoing translation work is tracked in [WAI Translations GitHub project](https://github.com/orgs/w3c/projects/46). Translation status in this project is updated by WAI team.

Got it! Thank you! @remibetin
