### ISSUE TITLE
preview banner

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-website#105]
> This is an unpublished draft preview. Please refer to our published website at w3.org/WAI/.

->

> This is an unpublished draft preview that might include content that is not yet approved. The published website is at <a href="https://www.w3.org/WAI/">w3.org/WAI/</a>

@yatil - what do you think?

**Comment by yatil** [comment]
Just seen and assigned it to me. I’ll make sure that the new banner is in stuff that is generated from next week on, if not earlier.

**Comment by slhenry** [comment]
Thanks! Good to get in business case soon -- before I send it to the AC list.

**Comment by yatil** [comment]
@slhenry done! I also made some minor changes to the business case (changing GitHub to relative links for the acknowledgement pages) and republished the preview.
