### ISSUE TITLE
[breadcrumb][LOW] separate with pipe instead of slash

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-website#106]
I **_mildly_** prefer

> Home | Accessibility Fundamentals | Perspectives Videos | Customizable Text

over:

> Home / Accessibility Fundamentals / Perspectives Videos / Customizable Text

Rationale:
* slash (/) is often used to indicate "or" in English
* pipe (|) visually ties in nicely with other vertical lines throughout the heading & nav area

I do not feel strongly and am happy to leave as is if others do.

**Comment by yatil** [comment]
Strongly for keeping the slash as it stands for hierarchy (like in a directory tree) where the pipe literally is used as or in programming languages and in other contexts. Also | can easily confused with l or I which has always been bad for usability and accessibility. Thirdly, the / is what we used tested with and we did not get one iota of feedback that it is difficult to understand.

**Comment by slhenry** [comment]
> slash (/) is often used to indicate "or" in English
> pipe literally is used as or in programming languages

So it comes down to English language vs. programming. ;-)

Agree with:
> | can easily confused with l or I which has always been bad for usability and accessibility

Re:
> the / is what we used tested with and we did not get one iota of feedback that it is difficult to understand.

We did not evaluate that in usability testing, so lack of feedback is irrelevant.


> I _**mildly**_ prefer | ...I do not feel strongly and am happy to leave as is if others do.
> Strongly for keeping the slash

Slash it is then.
