### ISSUE TITLE
Resources List

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-website#108]
https://www.w3.org/WAI/Resources/

update:
<del>
Possibly retire and:
- <del>[ ] redirect to sitemap
- <del>[ ] change links to it throughout site, e.g., https://www.w3.org/WAI/fundamentals/accessibility-intro/#more-info

<del>*or* Might keep, especially for [listing translations](https://github.com/w3c/wai-translations/wiki/WAI-Translations-Overall-Approach,-Issues,-Etc#list-of-resources-in-language)
</del>

**Comment by yatil** [comment]
@slhenry I think we should list translations on a separate page. And we need to look into generating the sitemap automagically from the navigation (which can now include sections that are hidden from the Main Navigation, like About WAI).

**Comment by yatil** [comment]
Attempt to implement something in #170 but ran into issues. I think we have to hand-compile the resources page as we don’t have the necessary data attached to the individual pages but as prose in the page itself. It looks like we cannot reuse it as we are doing too much custom stuff with it.

**Comment by slhenry** [comment]
Thank you for giving it a try.

I guess this is on my To Do list for after I finish the new Accessibility Fundamental Overview page for it.

Please let me know where you want the repo/page -- or just set it up and let me know.

**Comment by yatil** [comment]
I really like to have that done programmatically. I am worried about syncing it up with other pages and keeping it current.

**Comment by slhenry** [comment]
I'm confused. You said:
> I think we have to hand-compile the resources page

**Comment by yatil** [comment]
I think for now we have to hand-compile it, but I really like to do it programatically and I’m worried about syncing and keeping current. It is all true at the same time :-)

**Comment by slhenry** [comment]
:-)

**Comment by slhenry** [comment]
done by hand
