### ISSUE TITLE
Homepage: [W3C] - [WAI] - [You] boxes seem clickable but are not

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-website#11]
I kept clicking the boxes on the homepage "W3C", "WAI", and "You" until I figured that they are not interactive tiles but only static information.

**Comment by yatil** [comment]
They are not showing any behavior of clickable elements (hover/focus). We did user studies and the users found this to be the best version, iirc.

**Comment by slhenry** [comment]
This is a known issue and one we are still evaluating.

**Comment by slhenry** [comment]
They have been redesigned, and I'm pretty confident it takes care of this issue.
(not rolled out yet -- we'll let you know when so you can review)
