### ISSUE TITLE
wrapper for Understanding & Techniques pages

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website#110]
@yatil, reminder that we were going to figure this out.

@nitedog, I'm thinking we'll get something done soon, then your team can re-evaluate it with broader project work later.

**Comment by yatil** [comment]
What is there to figure out? I was expecting them to just use the PHP templates I provided to Michael… Or is there design/coding work that is needed? Maybe I just have to chat with @nitedog and Michael about this next week…

**Comment by slhenry** [comment]
This will be addressed with WAI-Guide project.
