### ISSUE TITLE
Social media etc links in footer

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-website#111]
Proposal:<br>In the footer, on a line after the tag line & before the Copyright line, add:

**&nbsp; &nbsp; &nbsp; [twitter icon] &nbsp; [feed icon] &nbsp; [YouTube icon] &nbsp; [[Get News in  Email](https://www.w3.org/WAI/news/subscribe/)]**

with:
* twitter icon = blue birdie
* feed icon = https://en.wikipedia.org/wiki/File:Feed-icon.svg
* YouTube icon = https://www.youtube.com/yt/about/brand-resources/
* "Get News in Email" button linked to https://www.w3.org/WAI/news/subscribe/

<hr>

Ideas for the last link:

Note: Resulting page title is "[Get WAI News](https://www.w3.org/WAI/news/subscribe/)" with links to WAI-Announce e-mail list, IG Discussion list, Feed, Twitter, YouTube, and All News page. The button on currently on home page that goes there is "Subscribe to WAI News"

* button-y-look (like in the home page) or plain text link? &mdash; plain text might look lost and awkward after the icons; button maybe good to match weight of the icons

1. [**Subscribe to WAI News**] &mdash; Twitter, Feed, YouTube are redundant with the previous icons in the footer. The only additional thing not already listed in the footer would be the e-mail lists; therefore, it seems best to include "e-mail" in the text (options below)
2. [**Get News Emails**] &mdash; best matches the title of the page
3. [**Get News in Email**] &mdash; best matches the title of the page
4. [**Get Announcement Emails**] &mdash; "Get" associates with resulting page title
5. [**Get Emails**] &mdash; shortest
6. [**Subscribe to Email**] &mdash; misses "Get" to associate with resulting page title
7. [**Subscribe to Get Email**] &mdash; short yet still clear and "Get" associates with resulting page title
8. [**Subscribe to Get News in Email**] &mdash; clearest but long
9. [**Subscribe to Get Announcements in Email**] &mdash; more technically correct since some announcements might not be "News". long

**Comment by yatil** [comment]
Ok

**Comment by bakkenb** [comment]
Proposal seems logical. Good placement. 
I like option #1 for the news button title.

**Comment by slhenry** [comment]
> I like option 1 ("Subscribe to WAI News") for the news button title.

@bakkenb I edited my original comment to clarify things. That's not a "news button". It goes to the [Get WAI News](https://www.w3.org/WAI/news/subscribe/) and that page has:
* **WAI-Announce e-mail list subscribing instructions**
* **IG Discussion e-mail list description and link**
* RSS/Atom Feed link (which is already in that footer line)
* Twitter link (which is already in that footer line)
* YouTube link (which is already in that footer line)
* News link to all previous news (which is in the list of links in the footer)

**Comment by yatil** [comment]
@slhenry I have deployed a prototype for this here:

https://deploy-preview-172--wai-website.netlify.com

<img width="983" alt="Screenshot 2019-07-02 at 13 24 18" src="https://user-images.githubusercontent.com/58862/60509229-b70f3780-9ccc-11e9-9ee5-b452183af175.png">

Please comment here (=not in the Pull Request) if you want changes (not urgent). I think we have to fine-tune the positioning. I’ll do that when we have agreed on the general concept :-)

**Comment by a11ycob** [comment]
Looks good, Eric. Thanks for this!

**Comment by slhenry** [comment]
Great, Eric!

I suggest two tweaks to the YouTube one:
* [ ] Include "YouTube" (like https://www.youtube.com/yt/about/brand-resources/) -- I think the arrow itself isn't clear enough. Also, we really want current and future videos to get attention.
* [ ] Link to [our playlist list](https://www.youtube.com/channel/UCU6ljj3m1fglIPjSjs2DpRA/playlistsv) -- I think that's the easiest way for users to see what videos are available.

Happy to entertain other ideas y'all have.

**Comment by yatil** [comment]
If we add text to one logo, we need to add them to all logos. I can do that. 

> Also, we really want current and future videos to get attention.

Unsure what that means, future videos, regardless of playlist will show up on the profile and get attention. Future videos will also get featured in news and maybe home page. Unsure how a “we are on youtube, too” link provides attention for those videos.

> Link to our playlist list -- I think that's the easiest way for users to see what videos are available.

This looks like the link I am linking too to me, the channel overview page: https://www.youtube.com/channel/UCU6ljj3m1fglIPjSjs2DpRA

(BTW we should be able to get a proper channel slug (youtube.com/w3c_wai ?) with more than 100 subscribers.)

**Comment by yatil** [comment]
>> Link to our playlist list -- I think that's the easiest way for users to see what videos are available.
> This looks like the link I am linking too to me, the channel overview page: https://www.youtube.com/channel/UCU6ljj3m1fglIPjSjs2DpRA
 

Oh, I now see the difference. We should be able to reveal the playlists on our channel page, but for now this will do.

**Comment by yatil** [comment]
I have added the labels to the links and also added the link to the playlists:

<img width="650" alt="Screenshot 2019-07-09 at 14 59 19" src="https://user-images.githubusercontent.com/58862/60889821-37e4ab00-a25a-11e9-917d-4af99c5ff30a.png">

https://deploy-preview-172--wai-website.netlify.com/

**Comment by yatil** [comment]
I might remove the underline from the links.

**Comment by slhenry** [comment]
+1 to removing the underline from the links

Youtube -> YouTube

**Comment by yatil** [comment]
I have published it, with the changes we discussed on Tuesday.
