### ISSUE TITLE
Add Page: Permission to Use WAI Material

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-website#113]
put this page into new design https://www.w3.org/WAI/about/usingWAImaterial

add link in footer - **_either_**:
* At the beginning of the Copyright line add "Permission to Use."
* At the end of the Copyright line add "Permission to Use."
* As a new line before the Copyright: "Permission to Use WAI Material"
* As a new line after the Copyright: "Permission to Use WAI Material"

whatever @yatil thinks is best.

note that we'll be adding a translation link to the list of links on the right, so it will become one line longer

(I marked it low priority, but kinda wanted "medium" because we keep getting asked and I keep pointing to the old page :(

**Comment by bakkenb** [comment]
+1 to move up in priority because of the emails lately.

**Comment by yatil** [comment]
page created here: https://w3c.github.io/wai-about-wai/about/using-wai-material/ 

I don’t feel strongly about any of the options. Please tell me what you think is best.

**Comment by slhenry** [comment]
Thanks, Eric!

To that page, I added summary, footer, and W3C "usage policies apply" link -- so we can replace it in our site-wide footer.

- [ ] In WAI site-wide footer, change "Usage policies apply." to "Permission to Use WAI Material." with link to that page

/me thinks the title of the page could be better, but not going to take time on it now.

**Comment by yatil** [comment]
Okay, I’ll add that to my queue!

/me also thinks we might look into making those policies simpler if possible. Currently, the page is a bit overwhelming instead of encouraging sharing. But not now :-D

**Comment by slhenry** [comment]
I'm getting a 404 from the link in the footer

Also, extra period at end:
> Permission to Use WAI Material..

**Comment by yatil** [comment]
I forgot to manually upload the page. The extra period is changed in the template and was to be corrected when I upload a new version.

All done now.
