### ISSUE TITLE
bullet color on home page, within content, and other 

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-website#114]
& square vs round

**Comment by yatil** [comment]
All bullets are round (as designed) and in text color (different than designed, as we have agreed on). – I personally find round bullets much more inviting than square ones but I don’t feel strongly enough to have a discussion.

**Comment by yatil** [comment]
#c0272d is --faded-red (as per https://w3c.github.io/wai-website-components/components/detail/colors.html)

Note that coloring the marker only is only supported very limited in browsers: https://caniuse.com/#feat=css-marker-pseudo

We might be able to use work around in those limited places. 

(Can you clarify what you mean by “main list of translations”? List left beneath the navigation?)

**Comment by slhenry** [comment]
> Note that coloring the marker only is only supported very limited in browsers: 

Right. so maybe image?

**Comment by yatil** [comment]
No images. 

> We might be able to use work around in those limited places.

**Comment by yatil** [comment]
@slhenry Is this still something we want to do? 

> _Proposal_ to get more color on the home page and draw attention and coordinate with upcoming proposals for translations:
> 
> * On home page, bullets under "Get Resources for…" are #c0272d
> * On home page, bullets under "Sponsors and Funders" are #c0272d
> * In main lists of translations, bullets are #c0272d

As the list in the header has no red bullets (which would draw a lot of attention), I don’t think we want them in the left list of translations underneath the side navigation (if that is what you mean with the “main list of translations”). 

I don’t feel 100% convinced that red bullets on the home page would be an improvement, but happy to implement them with the necessary work arounds for browsers that don’t support ::marker.

**Comment by yatil** [comment]
@slhenry A prototype is available here: https://deploy-preview-173--wai-website.netlify.com

Let me know if you want any more changes.

<img width="546" alt="Screenshot 2019-07-02 at 14 35 17" src="https://user-images.githubusercontent.com/58862/60513717-38b89280-9cd8-11e9-9260-78c98a186ecb.png">

<img width="546" alt="Screenshot 2019-07-02 at 14 35 25" src="https://user-images.githubusercontent.com/58862/60513714-35bda200-9cd8-11e9-82bd-f920c40a4c37.png">

**Comment by slhenry** [comment]
> On home page, bullets under "Get Resources for…" are #c0272d
> On home page, bullets under "Sponsors and Funders" are #c0272d

+1 

> In main lists of translations, bullets are #c0272d

I thinking this https://www.w3.org/WAI/translations/ but now it's DL and no bullets, so now it's not applicable :-)

Definitely *not* red bullets in translation list under the secondary nav.

[issue closed from my pov]
