### ISSUE TITLE
[low priority] Help improve this page box - different e-mail address

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-website#116]
Current box uses wai-eo-editors@w3.org

However, there are many pages where comments should not go to that e-mail address.

/me debates wai@w3.org vs. public wai-site-comments@w3.org ... decides on wai@w3.org because it will get more feedback (whereas people might not go through the hoop to approve their email for the public list)

/me will talk through options with Eric, and not write them all out here

For the wai@w3.org mailto, include in body text:

> [put comment here...]
> 
> I give permission to share this to a publicly-archived e-mail list.

**Comment by slhenry** [comment]
Default will be wai-eo-editors@w3.org (so we don't have to edit all existing pages!)

**Comment by yatil** [comment]
Just seeing:

> For the wai@w3.org mailto, include in body text:
>>
>> [put comment here...]
>>   
>> I give permission to share this to a publicly-archived e-mail list.

I’ll add this to all emails, wai-eo-editors is also a public mailing list, so it makes sense to me.

**Comment by slhenry** [comment]
Thanks, Eric! I'll work on changing the e-mail address for relevant pages.

> I’ll add this to all emails, wai-eo-editors is also a public mailing list, so it makes sense to me.

It's not needed for wai-eo-editors. The system already takes care of it.

We only need it for the wai@w3.org list so that we can forward a comment to a public list (or put it on GitHub).

**Comment by slhenry** [comment]
Initial replies below. Let's get in sync by phone tomorrow.

> So we need different treatments for different mail addresses?

Yes.

> Do we need that to be configurable on a per page basis?

?

> Will it be the same whenever a certain email is used?

Yes.

Only two options (that I can think of now):
* default is wai-eo-editors@w3.org - page name in subject is helpful. (nothing needed in body)
* some will have wai@w3.org - page name in subject is helpful + text in body from above.

**Comment by yatil** [comment]
If there are other options I need to know that before implementation.

**Comment by yatil** [comment]
from @slhenry [here](https://www.w3.org/WAI/EO/wiki/User:Eeggert/Work_Plan):

> I do not know of other options.
