### ISSUE TITLE
Breadcrumb bug

### ISSUE THREAD

**Issue by yatil** [w3c/wai-website#118]
An issue on different pages, including:

* from https://github.com/w3c/wai-intro-wcag/issues/29
* https://www.w3.org/WAI/standards-guidelines/wcag/20/glance/ (An archive page?)
* https://www.w3.org/WAI/business-case/acknowledgements/

**Comment by slhenry** [comment]
> https://www.w3.org/WAI/standards-guidelines/wcag/20/glance/ (An archive page?)

Note that I do not think we want to add "archive" to the URL.  Let's discuss if you think otherwise.

**Comment by yatil** [comment]
>> https://www.w3.org/WAI/standards-guidelines/wcag/20/glance/ (An archive page?)
> Note that I do not think we want to add "archive" to the URL. Let's discuss if you think otherwise.

I did not suggest that. (I just wondered where this goes into the navigation hierarchy, what the parent page is (probably just 2.1 at a glance). It was more a note to self.
