### ISSUE TITLE
news items seem clickable but aren't

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-website#12]
The homepage news item headings, like "Graphics-ARIA and Graphics-AAM wide review drafts", have a faint blue that look like a link. It took me a while to understand that I need to select the date(!) to expand the news item and get additional information. Why not make that heading a link too? Or add a "read more"?

**Comment by yatil** [comment]
TBH, those are not really designed yet. I have to think about how to approach it, especially where to put the date. (Prefix excerpt? In the heading? Underneath the heading in a smaller font?)

But I agree that the headings should be linked.

**Comment by slhenry** [comment]
(discussed with yatil - putting here ftr)

Our news blurb headings should not be clickable -- there is no additional info to get. They should not look clickable. (nor the date) Only the links inside are clickable.

I think the regular h3 style will work well for these. (will have to see in place to confirm)

**Comment by slhenry** [comment]
> especially where to put the date. (Prefix excerpt? In the heading? Underneath the heading in a smaller font?)

We really want to **downplay** the date. Why not leave it after the main blurb as it is in current site?
