### ISSUE TITLE
Archive "How to Change Text Size or Colors"?

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-website#122]
The WAI website previously had a page "How to Change Text Size or Colors", which was linked from the top right of all WAI pages. **[old version]( https://www.w3.org/WAI/changedesign.html)**

The **motivation** for that page was:
* Teach users how to change text and colors through their browser so it will work for them with other websites.
* Avoid people seeing changing widgets on the WAI site and assuming that they are required on websites for accessibility.
* Avoid insufficient or complicated changing widgets cluttering the WAI site design.

That page got out of date. It has not been a priority to keep it updated. Thanks much to Robert! for his work on the **[new version]( https://www.w3.org/WAI/meta/customize/), which is still an incomplete draft**

**We now would like the "screen real estate" of the top right for translations. [translations prototype](https://w3c.github.io/wai-translation-playground/people-use-web/), [translations beta](https://w3c.github.io/wai-video-standards-and-benefits/videos/standards-and-benefits/)** Note that the default view will list all translations, and some pages could have 20+ translations.

Options for what to do with the "How to Change Text Size or Colors" page:
* Archive it; not plan to update it.
* Archive it, and possibly update it in the future.
* Make it a priority to update it soon and maintain it.

_**If** keep it_, options for location of link to it:
* Put the link in the footer.
* Leave the link where it is (which will cause the language list to wrap much more).
* Put the link elsewhere ... ?where?

We'll discuss this in the 11 January EOWG telecon. Feel free to add considerations and rationale for your preference here now, or after the meeting.

**Comment by AndrewArch** [comment]
Can we assume our users are more tech savvy now than they used to be? Not so sure!

I had wondered about using an independent source for this, but even the BBC's [My Web My Way](http://www.bbc.co.uk/accessibility/) is _way_ out of date :(

How close is Robert's draft to being complete (I only skimmed)? If nearly there, then I'd support finishing with priority and linking from Footer as suggested. Otherwise archive.

**Comment by notabene** [comment]
> Can we assume our users are more tech savvy now than they used to be? Not so sure!

Same here, not sure.

For the record: +1 for keeping the article (it also works as a great EO reference for the world outside W3C) and link to it from the footer.
(I'll try to be on IRc during the meeting, but just in case, my vote is tracked here).

**Comment by slhenry** [comment]
> Can we assume our users are more tech savvy now than they used to be? Not so sure!

I still think **most people do _not_ know** how to change these settings in their browser. (Although probably most of the WAI website audience knows it more than the general audience.)

> even the BBC's My Web My Way is way out of date :(

Yeah, it says "This page has been archived and is no longer updated." As far as I can tell, they didn't replace it. Probably they decided it took too much to keep such information updated. (At least they left it there for archive.)

<hr>

Raw analytics data from 2018, since the redesign launch in May, is below.

Average time on page: 40 seconds

2,431 pageviews, which was <0.1% of all pageviews

Incoming traffic:
* 1,496 from internal pages
* 29 from internal searches
* 34 from search engines
* 0 from social networks
* 8 from websites
* 134 direct entries

Outgoing traffic:
* 1,009 to internal pages
   * 30% was to the WAI home page
   * 15% to https://www.w3.org/WAI/standards-guidelines/
* 20 internal searches
* 0 downloads
* 247 outlinks
   * 28% to https://support.google.com/chrome/answer/96810
   * 12% to https://support.mozilla.org/en-US/kb/font-size-and-zoom-increase-size-of-web-pages ; 
   * 10% to https://support.microsoft.com/en-us/help/17456/windows-internet-explorer-ease-of-access-options
   * 12% to create New GitHub Issue (although none were created)
   * 09% to Fork & Edit on GitHub (although no pull requests were submitted)
* 673 exits

<hr>

I think the overall issue is the people-resources needed to get it up-to-date and keep it up-to-date, versus the number of people who find it useful.

Also, if we move it to the footer, it's likely even fewer people will find it.

For the record: I am generally a strong proponent of it, and previously defended it. I'm just being swayed by the priorities of screen real estate and other work...

**Comment by slhenry** [comment]
input from [11 January EOWG discussion](https://www.w3.org/2019/01/11-eo-minutes.html#item04)

* Keep the page. Robert will update it!
* Consider options for including the link at the top. (icon without text?)

**Comment by slhenry** [comment]
Another thought: Previously the top bar had only "Skip to Content | Change Text Size or Colors" right aligned. When we add the list of languages, button, and "All Translations [icon]", that area of the site will likely get more attention. Thus, if we leave Change Text Size or Colors around there, it may get seen even more than it did in the past.

**Comment by slhenry** [comment]
See [**options** with straw proposal](https://www.w3.org/wiki/WAI_Translations#Including_Change_Text.2C_Colors) for:
* including "Change Text Size or Colors"
* no icon
* making collapsible everything after "Skip to content" (similar to current translations UI for mobile)

**Comment by yatil** [comment]
We’ll keep the page.
