### ISSUE TITLE
nav tweaks for consistency & usability

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-website#126]
- [x] SLH: Create an "Accessibility Fundamentals Overview" page similar to the others. https://github.com/w3c/wai-fundamentals-overview/pull/3
- [ ] SLH: Consider the title of "Evaluating Web Accessibility Overview" & the nav "Test & Evaluate", and the title of "W3C Accessibility Standards Overview" (for nav Standards/Guidelines)
- [x] yatil: Make the first text in the secondary nav area link to the overview page (and remove "overview" link) -> #154
- [ ] whoever: change "and" to "&"  in overview page titles so it doesn't bug yatil ;-)

**Comment by yatil** [comment]
I can address #154 (and here bullet point 3) when the Accessibility Fundamentals Overview Page is ready. The other points have no impact on me making the change technically.

**Comment by slhenry** [comment]
> I can address #154 (and here bullet point 3) when the Accessibility Fundamentals Overview Page is ready. The other points have no impact on me making the change technically.

Thanks! Done. (I'll QA is once preview available.)

**Comment by yatil** [comment]
Now I’m confused after I worked on this for a couple of hours today… Is it done or does it need QA? 

Preview has been available since before your comment at w3c/wai-fundamentals-overview#3…

**Comment by yatil** [comment]
Here’s how it looks (Blue when on another page, you can view how it behaves in the https://wai-website-theme.netlify.com/ preview.)

**Comment by slhenry** [comment]
Preview took a little bit. I did quick spell check. That's good enough for now.

**Comment by yatil** [comment]
My parts of this issue are done.
