### ISSUE TITLE
consider decreasing space above H2 (and maybe others)

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-website#128]
& maybe before "Help improve this page" box

requested by Judy

**Comment by yatil** [comment]
We already did that several months ago. Readability is paramount and being able to distinguish sections is, too. I personally would add more spacing around headings for easier skimmability.

**Comment by slhenry** [comment]
update: we have a style for this, but I'm not sure it's well documented, nor working....

**Comment by yatil** [comment]
You do and it is: https://wai-website-theme.netlify.app/writing/frontmatter/#class

**Comment by slhenry** [comment]
Added to documentation where I would look for it. https://wai-website-theme.netlify.app/components/headings/#space-before-headings
