### ISSUE TITLE
[low-medium] Consider adding Twitter feed to home page

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-website#129]

**Comment by yatil** [comment]
-1 unless we change what we tweet, currently we mostly tweet our news. Also huge privacy implications (as we have to use Twitter's embed code, sending all info to them).

**Comment by slhenry** [comment]
Hi @a11ycob, Per above, we're not going to add Twitter now for.

**Comment by yatil** [comment]
@slhenry Wait, what? Having a _link to twitter_ (that @a11ycob asked for) and _the twitter feed_ are two different things. We **do** want the first one, we imho do not want the second one.

**Comment by slhenry** [comment]
link to Twitter is covered in https://github.com/w3c/wai-website/issues/111
closing this issue for twitter feed.
