### ISSUE TITLE
Please don't open menus on hover (unless user has already clicked to open)

### ISSUE THREAD

**Issue by carmacleod** [w3c/wai-website#14]
Menus shouldn't open on initial hover.
Instead, only open if the user clicks, or types enter/space, on a menubar item.
If a menu is **already open**, it is ok to open another menu if the user hovers over that menubar item.

That way, you know that the user actually intended to look into the menus; you are not making any assumptions for them.

This blog post describes [some problems with hover menus](https://medium.com/simple-human/why-hover-menus-are-problematic-b21d6c7de91c).

For me, even though I know that hover menus are everywhere, it still startles me, every time I happen to move the mouse over a menubar, to have something unexpectedly fly in my face and obscure what I was just about to read.

**Comment by slhenry** [comment]
Thank you for the input. This is one of the issues we are still evaluating.

In usability testing, participants preferred the menu opening on hover.
However, we are aware that others do not.

**Comment by carmacleod** [comment]
> In usability testing, participants preferred the menu opening on hover.

Interesting. I'll see if I can get some others to give their opinion.

**Comment by yatil** [comment]
Yeah, I’m personally not a fan of hover menus, but the user research showed that it is an expectation especially for non-disabled participants. (We had a click to open menu to test with, iirc.)

**Comment by mfairchild365** [comment]
I agree that using hover to activate controls is usually a bad pattern. However, I have found that it is an expected action when it comes to menus, so I echo @yatil's comment. 

Perhaps a compromise would be to use [the hover intent pattern](https://briancherne.github.io/jquery-hoverIntent/). There are a few different js libraries that you could use to accomplish this.

**Comment by goetsu** [comment]
I've seen similar result during user test but not when you are on the burger menu version. In that case you must go back to onclick/touch

**Comment by yatil** [comment]
FWIW, I think the hover intend examples take way too long to react, my brain goes either “this has no sub menus, click” (could be better with an appropriate icon indicating a submenu) or, when it eventually opens, this is slow, something is wrong with the website (might be better with a shorter wait time than in the examples). 

Also, we are planning to move away from the fly out as it did not really “click” in the context of the whole site.

**Comment by carmacleod** [comment]
Ok. Looking forward to seeing what you replace it with.
PS: Nice pun!  :)

**Comment by slhenry** [comment]
+1 to closing this issue now that we've moved away from the drop-down/fly-out menu.

**Comment by yatil** [comment]
Will be addressed with #34.
