### ISSUE TITLE
RTL todos

### ISSUE THREAD

**Issue by yatil** [w3c/wai-website#145]
Todos for Right to Left Languages:

Preview on: https://deploy-preview-50--wai-video-standards-and-benefits.netlify.com/videos/standards-and-benefits/ar

- [x] Table text alignment is fixed to left-aligned, needs to be the same direction as the main text.
- [x] Date is not aligned properly, likely a bidi issue (rel: https://www.w3.org/International/techniques/authoring-html?open=direction#direction) – we will have lots of those, and they are hard to detect, so I expect a lot of need for testing here.
- [ ] CSS needs to be adapted to be RTL-ready, including header and footer

**Comment by ntounsi** [comment]
Few points.

1) Table content is left aligned instead of right. 
There is a "`table{text-align:left}`" inherited from CSS. 

In the `<tbody>` element of `<table>`, attribute `dir="rtl"` is added. Is it possible to add `text-align:right` also? 

2) Dates are still in wrong rendering: `Mar YYYY DD` instead of `YYYY Mar DD`. Is it possible to put it like `YYYY-Mar-DD` with dashes or something like? Another work around is to span it with `dir="ltr"`.

3) About The blue banner at the top. For the Arabic part (_Strategies_, _Standards_ ...), I inspected the element and hacked to override some inherited styles (s/left/right/):

```
.logos .claim {
	font-style: normal;   /* Italic is not an Arabic style in general*/
	padding-right: 16px;  /* To better align the Arabic */

	border-right:1px solid var(--gold); /* To get the yellow vertical line*/
	margin-right: 16px; /* to get it aligned */
}
```

Please verify if it is coherent with your design.

4) I'm now inspecting the line on the very top of the page (with translations links etc.), to try to have it look like the original. Alignment and padding are not good.

**Comment by yatil** [comment]
Thanks, @ntounsi, I had those on my plate. 3 and 4 are all CSS issues where we didn’t do anything yet :-D

**Comment by yatil** [comment]
Hi @ntounsi, a quick question about the following:

> About The blue banner at the top. For the Arabic part (Strategies, Standards ...), I inspected the element and hacked to override some inherited styles (s/left/right/):
> 
> ```css
> .logos .claim {
>	font-style: normal;   /* Italic is not an Arabic style in general*/
>	padding-right: 16px;  /* To better align the Arabic */
>
>	border-right:1px solid var(--gold); /* To get the yellow vertical line*/
>	margin-right: 16px; /* to get it aligned */
> }
> ```

I guess the Arabic font gets “slanted” (fake italics) if `font-style: italic` is used and that is not desired, right? I’m OK with removing the italic emphasis from the header, but I wonder what to do about the emphasis in inline-text.

I found [this PDF](https://web.archive.org/web/20160304100215if_/http://ctan.mackichan.com/macros/xetex/latex/arabxetex/arabxetex.pdf) which says:

> Emphasis in Arabic is traditionally indicated by overlining the text

So do you think it would be appropriate to use something like this CSS to add overlines for the main content:

```css
em {
  font-style: italic;
}

main:lang(ar) em {
  font-style: normal;
  text-decoration: overline;
}
```

And just for confirmation: Setting fonts bold is a good way for strong emphasis, or should we do something in addition there, too?

**Comment by ntounsi** [comment]
Arabic italic can (should) be slanted the other side to the left. I know of "Amiri" font doing this.
![amiriSlanted](https://user-images.githubusercontent.com/15004708/55473020-72103200-5605-11e9-8ad9-b0d85e55ad18.png)

According to what I've seen, emphasis in Arabic can also be done : 
1) By changing the font of the text to be emphasized. In general by choosing a visually more stylistic font, e.g. a good Naskh font in Arabic like the Amiri font.
![amiri](https://user-images.githubusercontent.com/15004708/55473352-6bce8580-5606-11e9-839c-df8c62bbe693.png)
2) By putting some «» around the text
![guillemets](https://user-images.githubusercontent.com/15004708/55473426-a0dad800-5606-11e9-9bbc-58aac1955894.png)
Or some other kind of ornate parenthesis to wrap the text, e.g. U+FD3E/U+FD3F.
3) By adding diacritics to the text  (Vowelization)
![diacritics](https://user-images.githubusercontent.com/15004708/55474390-edbfae00-5608-11e9-976a-228beb8e36a0.png)
4) Or some combination of all these
![diacriticsAmiriItalic](https://user-images.githubusercontent.com/15004708/55474557-5eff6100-5609-11e9-9870-90dfef6cfae8.png)

In the context of this page, **2) or 3)**  has the advantage the touch the content not the CSS.
(my preferred would be 1) or the left-slanted font)
Overline is rarely used. IMO it would not be good here.

**Comment by yatil** [comment]
@ntounsi That's super insightful, thank you!

Noto Sans, the font we use, has an Arabic variant: https://www.google.com/get/noto/#sans-arab

It looks like they did not implement left-leaning italics, so I think we don’t have a way to support them. I’m happy with 2 or 3. 2 could be implemented in CSS, or we document it for translators to do it manually. 

```css
main:lang(ar) em:before {
  content: "»";
}
main:lang(ar) em:after {
  content: "«";
}
```

**Comment by yatil** [comment]
@ntounsi @slhenry  FYI I just shipped an update. Still some CSS issues, but we’re getting there: https://deploy-preview-50--wai-video-standards-and-benefits.netlify.com/videos/standards-and-benefits/ar

**Comment by ntounsi** [comment]
Yes. Looks good now.
The list on the top of the page is OK
- Date is still to fix ( 24 Mar 2019) 
- Emphasis in the header, italic?
- Remove an extra &amp; in the UI button corresponding to "Fork & Edit on Github" at the bottom of the page.
- (A personal opinion) I would prefer the font noto-arabic-naskh instead of noto-arabic-sans.

**Comment by slhenry** [comment]
@yatil, extra & fix is [here](https://github.com/w3c/wai-website-data/commit/035783734a7ec643b21b7e5bd3cabceb42d6093e#diff-9d31a970248a8964164d48b618b6060b)

**Comment by ntounsi** [comment]
A typo fixed [here](https://github.com/ntounsi/wai-website-data/commit/9594ab3c3d4b43b343f514b48395bb15332cfdaf)

**Comment by yatil** [comment]
Thank you both! 

> (A personal opinion) I would prefer the font noto-arabic-naskh instead of noto-arabic-sans.

Happy to change the font. I’ll correct the CSS details (italic text, some alignment) next and let you know when a new preview is ready.

**Comment by yatil** [comment]
@slhenry @ntounsi I couldn’t hold back, so I have made a couple of updates. I think, unless we find major issues, I would be comfortable launching at this stage. Here’s the preview:

https://deploy-preview-50--wai-video-standards-and-benefits.netlify.com/videos/standards-and-benefits/ar

**Comment by ntounsi** [comment]
@yatil Great! 

Just a small issue in the other languages page. In the list of languages (on the top, and on the left side), "Arabic" is written with letters not connected. 
The style being
`body:not(:lang(ar)) :lang(ar) {
    font-family: Noto Naskh Arabic Minimal,Noto Sans,Trebuchet MS,Helvetica Neue,Arial,sans-serif;
}`

Removing `Minimal` from `Noto Naskh Arabic` would solve the problem. (BTW, Why `Minimal`?)

**Comment by yatil** [comment]
@ntounsi I tried to create a smaller version of the font that only has the letters for “Arabic” to use on the non-Arabic pages (as the full Arabic font is rather large). It looks like the font subsetting broke the connection of the letters. I can try to fix it, but we can launch with the system font on non-Arabic pages if I don't get to it timely.

(Basically, I think it would be nice if the font wouldn’t change when switching the pages but it is probably more a nice-to-have :-D)

**Comment by yatil** [comment]
@ntounsi I managed to fix it :-) Turns out that this is an OpenType feature that should not be removed :-o

**Comment by ntounsi** [comment]
Any idea why there is a horizontal scroll bar on the bottom of the window's page?

**Comment by yatil** [comment]
@ntounsi I don’t see a horizontal scroll bar. Can you give me details on the browser and operating system you use?

**Comment by ntounsi** [comment]
I got a similar problem once, due to an off-screen position for a hidden content.

**Comment by ntounsi** [comment]
Here is a screen capture. Scrolled a little  to the left (Firefox)

![scrollH](https://user-images.githubusercontent.com/15004708/55546690-c4198c00-56c7-11e9-982e-6bddfd894c0a.png)

**Comment by ntounsi** [comment]
Same problem with Chrome. I'm on MacOS High Sierra.

**Comment by yatil** [comment]
@ntounsi Oh, now I see it, too! Interesting! :-o

**Comment by yatil** [comment]
@slhenry @ntounsi I fixed the horizontal scrolling:

https://deploy-preview-50--wai-video-standards-and-benefits.netlify.com/videos/standards-and-benefits/ar

Can we publish? :-D

**Comment by slhenry** [comment]
Exciting! +1 for publishing now.

@ntounsi - if you feel it's OK, we would like to publish now. We can continue to polish and refine it if there are other minor fixes we want to implement.

**Comment by ntounsi** [comment]
@slhenry @yatil Congratulations! 
++1

**Comment by yatil** [comment]
@slhenry @ntounsi And we are online! If you spot any further issues, create a new issue here in this repository: https://github.com/w3c/wai-website/issues/new?title=%5BRTL%5D%20

**Comment by yatil** [comment]
Ooops, link to the online version: https://www.w3.org/WAI/videos/standards-and-benefits/ar
