### ISSUE TITLE
Two pages edited directly on server

### ISSUE THREAD

**Issue by yatil** [w3c/wai-website#146]
Trying to update the website I saw that two pages have been updated in CVS directly:

* https://www.w3.org/WAI/translations/
* https://www.w3.org/WAI/about/groups/eowg/

I did not get a notification about them being updated on GitHub, too, so I did not update those pages. Please let me know when/if I can overwrite them.

**Comment by slhenry** [comment]
Overwrite away. Changes done in GitHub, too:
* https://github.com/w3c/wai-about-wai/commits/master/_about/translating.md
* https://github.com/w3c/wai-about-wai/commits/master/_about/groups/eowg.md

**Comment by yatil** [comment]
Just drop a short email :-) or mention me in the commit, like: @yatil content of manual overwrite
