### ISSUE TITLE
Menubar needs even more keyboard capability

### ISSUE THREAD

**Issue by carmacleod** [w3c/wai-website#15]
Currently, if a menubar item has focus, the menu can be opened with Enter.
That's great, but they should also open with Space, Down arrow, and even Up arrow.

Then, once a menu is open, typing Tab moves focus through the menu item links in sequential order.
That's ok base functionality, but I think that up/down arrows (and even right/left arrows) should also focus the menu item links in row/column order, wrapping as needed.

Of course, Esc should close an open menu, but I think you already have a issue for that.

**Comment by yatil** [comment]
I’m not a big fan of using application menu shortcuts for navigational menus – most non-screenreader keyboard users don’t know about them and there is no indicator for it to be one or the other. That said, I think up and down keys are pretty save things to enable. I’ll also add space.

**Comment by slhenry** [comment]
+1 to closing this issue now that we've moved away from the drop-down/fly-out menu.

**Comment by yatil** [comment]
Will be addressed with #34.
