### ISSUE TITLE
Remove navigation header, use section header as navigation title instead of overview

### ISSUE THREAD

**Issue by yatil** [w3c/wai-website#154]
from #126:

- [x] Make the first text in the secondary nav area link to the overview page (and remove "overview" link)

**Comment by slhenry** [comment]
Waiting for Shawn to finish Accessibility Fundamentals overview page, right?

**Comment by yatil** [comment]
Done.

**Comment by slhenry** [comment]
woo-hoo! Great!

... looks like maybe bug in https://www.w3.org/WAI/teach-advocate/

**Comment by yatil** [comment]
The code was updated 2 hours ago. It looks like there is some caching issue on the W3C server. nothing I/we can do. https://cvs.w3.org/Team/WWW/WAI/teach-advocate/index.html?rev=1.70;content-type=text%2Fplain

**Comment by slhenry** [comment]
maybe also bug here https://www.w3.org/WAI/policies/ ?

**Comment by yatil** [comment]
Different bug as this uses a different Template and we hadn’t specified how the change applies to those templates.
