### ISSUE TITLE
Print Stylesheet Refinements

### ISSUE THREAD

**Issue by yatil** [w3c/wai-website#156]
- [ ] Expand/collapse should be expanded
- [x] Footer styles
- [x] Help improve this page styles

**Comment by yatil** [comment]
rel: #181

**Comment by HerinHentry** [comment]
Hi @yatil, Can we please increase the print-font size to 12pt instead of 10pt? 

Reference: [Written Communication - Printing ](http://universaldesign.ie/Products-Services/Customer-Communications-Toolkit-for-the-Public-Service-A-Universal-Design-Approach/Written-Communication/Printing/)

**Comment by yatil** [comment]
@HerinHentry I was just recently asked to use smaller fonts (especially for headings, but of course they are in relation to the body text). I guess I have to get back and define print-specific font sizes…

**Comment by yatil** [comment]
@HerinHentry I made the change. You might need to force reload the site as we tend to cache quite aggressively.
