### ISSUE TITLE
Reintroduce “Suite” or “Resource” Sub-titles

### ISSUE THREAD

**Issue by yatil** [w3c/wai-website#157]
This is basically reopening #45 as we implement the navigation changes in #154.

**Comment by yatil** [comment]
This will be possible in the future, as I am implementing a way that helps to do this here: https://github.com/w3c/wai-website/pull/167

**Comment by yatil** [comment]
@slhenry Please send feedback on this prototypical implementation:

https://deploy-preview-87--wai-people-use-web.netlify.com/people-use-web/user-stories/

<img width="587" alt="Screenshot of prototypical implementation" src="https://user-images.githubusercontent.com/58862/60498808-8ffa3b00-9cb7-11e9-8c00-5d92f5657842.png">

**Comment by slhenry** [comment]
Thanks, Eric, I'm really glad to see this getting done. I especially think we need it for the media resource and for the translations list.

I debated italics or not. (... Italics harder to read. Italics good for titles. Italics good to set it apart...)
I guess OK to go with italics for now. (could change it later we get convincing feedback)

I think no colon -- so just:

> _in [How People with Disabilities Use the Web](@@)_

Then , good to go and close this issue when you want to.
