### ISSUE TITLE
May want to tweak the keyboard operation of the drop down menu

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/wai-website#16]
Currently the drop down main menu is tab driven... consider the wai-aria authoring practices model.
https://www.w3.org/TR/wai-aria-practices-1.1/#menu

Where the user tabs into the menu and uses arrow keys to navigate once inside.
If this model is not chosen and tab is used to move through the list of  links, then I think a response on why not would be good, because there is an active discussion about whether a tab navigated menu should be included in the authoring practices document.
https://github.com/w3c/aria-practices/issues/492

At least trap the esc key to close the menu.

**Comment by yatil** [comment]
See also #9, #14, #15. 

Thanks for your feedback.

As the discussion in the ARIA practices thread shows there is not a clear consensus on what to do. If we use ARIA’s application menu, I personally think we need to go all-in with the keyboard interactions described in the ARIA Practices Guide if we decide to use some of them. 

However, those keyboard interaction pattern might be unknown to some keyboard users in the context of we pages and there’s not a good way to communicate it to non-AT keyboard users. 

We plan to add additional keyboard capabilities during the beta and monitor the thread over at the ARIA Practices repository for consensus and advice. 

(Note: this is also an approach that we took in the [WAI Accessibility Menus Tutorial](https://www.w3.org/WAI/tutorials/) and we are looking into adapting our guidance there.)

Thanks again for your feedback, David!

**Comment by slhenry** [comment]
+1 to closing this issue now that we've moved away from the drop-down/fly-out menu.

**Comment by yatil** [comment]
Will be addressed with #34.
