### ISSUE TITLE
footer id ?

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-website#162]
Hey @yatil ,

I occasionally want to send someone a link to the footer of a page. Does it make sense to add an id to the template?

~Shawn

**Comment by yatil** [comment]
@slhenry Deploying an update that adds `wai-page-footer` and `wai-site-footer` IDs to the pages. (prefixed with `wai-` to avoid collisions with automatically generated IDs in the content.)

**Comment by slhenry** [comment]
ok.

thanks.
