### ISSUE TITLE
table color option quiet

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-website#165]
Hey @yatil ,

I know we've talked about this before, and I cannot find or remember if we already have an issue for it -- or if it's already done.

Current visual design has extremely strong table headers, with the white text on eye-catching background. That may be OK for tables that we really want to jump out on a page. That's not good for tables that we do not want to jump out.

I and other EOWG folks want a table visual design option that is quieter -- regular color text on regular color background, with headers bold (and keeping those light separator lines).

I'd like this for the media resource -- so in June 2019.

Let me know if you need more info.

Thanks!!!

[update:] /me re-reads Rachel's suggestion... make the header background the same light gray as in the header of the boxes like "Summary" at the top... that's probably a good idea -- so the table headers are slightly-more distinct than just bold.

**Comment by yatil** [comment]
@slhenry Done.

Use `class="quiet"` to invoke the new style. It can be used with the `dense` style as well: `class="quiet dense"` to create more compact tables with a quiet appearance.

**Comment by yatil** [comment]
https://w3c.github.io/wai-website-components/components/detail/tables-quiet.html
