### ISSUE TITLE
TOC - more control over what's in and out

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-website#169]
I'm finding that I want some level 3 headings in a TOC, and not others.

Would you add functionality for tha. :-)

Let's chat briefly so we can get in synch.

priority/timing: Would like for media resource within the next couple weeks.

**Comment by yatil** [comment]
> Would you add functionality for tha. :-)

It’s already built-in! Write:

```markdown
### Heading Level 3
{:.no_toc}
```

(This is the Markdown notation for “add class `no_toc` to the H3”.)

We use it here to not have ”Introduction” in the TOC:
https://www.w3.org/WAI/test-evaluate/conformance/wcag-em/

> Let's chat briefly so we can get in synch.
> 
> priority/timing: Would like for media resource within the next couple weeks.

I hope that was quick enough ;-) More useful bits can be found in the documentation of our Markdown parser: https://kramdown.gettalong.org/quickref.html

**Comment by slhenry** [comment]
I love it when I want something and you've already done it!!! ;-)

(Now I just gotta figure out where I hacked heading levels and fix 'em. :)

**Comment by slhenry** [comment]
> More useful bits can be found in the documentation of our Markdown parser: https://kramdown.gettalong.org/quickref.html

Please add link to that in the documentation so I can find it later... :-)
