### ISSUE TITLE
Visited links in primary and secondary nav turn black

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-website#171]
Mac, dark mode, Chrome:

<img width="674" alt="IMPORTANT dark visited links" src="https://user-images.githubusercontent.com/6991814/60279256-534ccf00-98c6-11e9-96f3-4e5cc23e41f2.png">

<img width="675" alt="IMPORTANT chrome settings" src="https://user-images.githubusercontent.com/6991814/60279268-58118300-98c6-11e9-91a0-6dca481d4f3b.png">

If needed, I can get you in contact with the owner of the system.

**Comment by yatil** [comment]
Works fine in the current release version of Chrome (75), the version shown above is a pre-release version (Canary) that is also outdated (“Relaunch Chrome to finish updating”).

It might be good to either update to the latest version of Canary to see if the chrome bug is addressed. We do not support beta software and our CSS is working fine. Also, there are several plugins installed which might break the CSS.

See screenshots from the current release version below:

![Screenshot 2019-06-27 at 17 56 07](https://user-images.githubusercontent.com/58862/60281239-de4cba00-9904-11e9-9aa2-c45dd8251f3d.png)

![Screenshot 2019-06-27 at 17 56 12](https://user-images.githubusercontent.com/58862/60281244-e3116e00-9904-11e9-9ab6-900deba3e7f6.png)

**Comment by yatil** [comment]
And I just verified here that it seems to work as expected on the latest Canary as downloaded from here: https://www.google.de/intl/en_us/chrome/canary/

**Comment by slhenry** [comment]
Thanks @yatil !
