### ISSUE TITLE
List with images

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-website#177]
In https://wai-media-guide.netlify.com/design-develop/media/#how-to-make-audio-and-video-accessible --  make the AD, CC, transcripts, & sign items a list

with hanging indents!

Also for https://www.w3.org/WAI/standards-guidelines/w3c-process/#milestones
(We had those as hanging indents in old design, but it got lost moving over to the new site.)

**Comment by yatil** [comment]
@slhenry This has now been added, with a responsive fallback in the theme. Preview/Code example: https://wai-website-theme.netlify.com/components/lists/#nolistimg

**Comment by slhenry** [comment]
Thanks Eric.

> Note:
>* On mobile: 100px wide with text floating around.
>* On desktop: 150px wide with text floating next to it (space underneath the image).

For https://wai-media-guide.netlify.com/design-develop/media/#how-to-make-audio-and-video-accessible we need much smaller. More like 75px for desktop

**Comment by yatil** [comment]
@slhenry I have added size classes to the list.

**Comment by slhenry** [comment]
Great!

> More like 75px for desktop

I'd like to change my mind now that I see it implemented. 

> Size classes:
>* tiny: 60px
>* mini : 75px
>* small : 120px
>* normal: 240px
>* large : 480px

s/mini : 75px/mini : 90px

/me would be happy to make the change herself!

**Comment by slhenry** [comment]
so... how difficult would it be to link the images? :-)

**Comment by yatil** [comment]
> /me would be happy to make the change herself!

I did it for now. In the future: Check the wai-website-theme out locally, edit the CSS files, run the `gulp css` task and commit the changed files. More in-depth documentation is coming and I hope that GitHub Actions can help us taking running the task runner locally from us, but that time is not now. Documentation around this is in the making.

> so... how difficult would it be to link the images? :-)

You can just use normal links around an image, so I guess the answer is “not difficult”? :-)
