### ISSUE TITLE
[low] print css - smaller headings, especially h1

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-website#181]
Firefox Windows (and Shawn's size settings):
![image](https://user-images.githubusercontent.com/6991814/62147813-004baa80-b2be-11e9-8e63-d5ac07b83902.png)

**Comment by yatil** [comment]
Here are PDF prints of [Safari](https://github.com/w3c/wai-website/files/3450383/safari.pdf) and
[Firefox](https://github.com/w3c/wai-website/files/3450385/firefox.pdf), Firefox produces larger fonts for some reason. It should not. Unsure if I’m able to fix that without making fonts elsewhere tiny.

The base font size is set to `10pt` for print: https://github.com/w3c/wai-website-theme/blob/master/_css/base.css#L145

**Comment by slhenry** [comment]
Chrome Windows:
![image](https://user-images.githubusercontent.com/6991814/62261354-a7256900-b3da-11e9-9bff-bf9a320b3336.png)

**Comment by slhenry** [comment]
+1 for not making fonts tiny -- better too big than too small !

All above, including Safari, have the h1s way too big. And I think the h2s too big, too.
Note: We have good spacing (some say too much, yet I don't :-) before headings, which means we can have a little less size difference from the body text.

Caveat: My settings are uncommon to accommodate my visual processing. I think I did the images above at 100% zoom to try to be "normal"-ish ;-)
Use Case: In reality, when I print things, often I just use print zoom. For our site that makes the headings crazy-too-large and with the spacing above, it's a waster of paper. (Sometimes I do save and customize the CSS - just more work.)

Please consider common settings (not mine). I *think* still good to make the headings in print CSS smaller. However, if disagree, OK. Can close this issue.

**Comment by yatil** [comment]
Hm. I personally don’t think the headings are too big, but that’s just personal preference :-) I’ll look into it. (noting the [low] priority)

**Comment by yatil** [comment]
A change that I made yesterday has reduced the font-size of headings in print (while keeping the ratios intact). Firefox is still outputting large-ish body text. 

(Resources need to be updated to get the new CSS file from the theme.)

**Comment by slhenry** [comment]
Hi Eric,

I guess I didn't communicate my issue well, because "... reduced the font-size of headings in print (while keeping the ratios intact)" is the **opposite** of what would work best for me.

I need the **headings _smaller in proportion_** to the main text. And main text bigger is better.

Note that when I need to print pages, the quickest way is to just zoom until the main text that I need to read is big enough. With the page above, that means the headings get huge and it wastes a lot of paper.
![print-top](https://user-images.githubusercontent.com/6991814/63363070-8d6fa580-c338-11e9-9b1b-162b73b0f7ea.png)
![print-bottom](https://user-images.githubusercontent.com/6991814/63363382-1c7cbd80-c339-11e9-8ba9-57364b76053d.png)

<hr>

Note that advanced users who need large text and create their own CSS, often making headings fairly small (and use other cues to indicate that headings) because headings are often short and easy to read and we don't want to waste space for the headings. [real-life examples of css for reading online](http://www.tader.info/ex-displays.html)

(I'm **not** suggesting that for our print CSS -- because it would be unusual and added cognitive load to figure out heading cues -- and kinda ugly. :-)

<hr>

I realize all above is for people who need larger print.

I still think for the default print, we should have smaller headings and larger main text than is currently -- to optimize readability and paper-usage

Of course, we still want the headings to be distinct, and thus bigger. It already has spacing and bold and underlines, to help distinguish heading levels.

**Comment by yatil** [comment]
I’m working on much reduced heading sizes as we speak in relation with the other issue.

**Comment by yatil** [comment]
Font sizes are now:

h1 -> 24pt
h2 -> 21pt
h3 -> 16pt
h4 -> 14pt
h5 -> 12pt
h6 -> 12pt
