### ISSUE TITLE
video links

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-website#187]
Current options: https://wai-website-theme.netlify.com/components/video-links/

Would also like:
* large image &mdash; like under [Introduction](https://wai-media-guide.netlify.com/design-develop/media/description/#introduction) (those dimensions or close as  you see fits best)
* ```in-line link<br>image``` &mdash; like under [Example Video](https://wai-media-guide.netlify.com/design-develop/media/#example-video) (that works with different size images)

Let me know if you need more info or want to discuss. Thanks!

**Comment by yatil** [comment]
> large image — like under Introduction (those dimensions or close as you see fits best)

And that is supposed to be linked? I don’t see how we can do both specifications with a template. There is text inside and outside the link and line breaks that seem not follow any type of formality. (Every video link looks different.)

I think I’ll remove the template completely, give you a class for rounded corners for the images and be done with it. Too bad, I really hoped we would have easy to recognize video links.

**Comment by yatil** [comment]
Images have now a helper and can get several classes, including `video`. So you can use the video style as you please. The previous video-link helper has been depreciated.

https://wai-website-theme.netlify.com/components/images/
