### ISSUE TITLE
Tips pages

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-website#2]
Have left side Related Links section include all 6 Tips pages?

**Comment by yatil** [comment]
This is not in the IA I got (I only got the navigation and the navigation spread them over the categories). It would be disorienting. I can change the IA, of course, but it was never communicated that this was one resource.

**Comment by yatil** [comment]
I put the tips into their own resources and changed all links in the navigation. Now they are not inside one category, which is something that no other resource is doing.
