### ISSUE TITLE
Revisit WAI focus indicator?

### ISSUE THREAD

**Issue by hidde** [w3c/wai-website#200]
From https://github.com/w3c/wai-authoring-tools/issues/44:

> The focus indicator is generally a dark blue outline. I wonder if a more visually salient colour could be used. Gov.uk have a gold outline for focus styling on form elements, and a full block for links. This makes the elements much more visually salient. 

Opening this here instead of in the Authoring Tools List repository. I don't have strong feelings and like the indicator we currently have, as well as the one GOV.UK have.

**Comment by yatil** [comment]
The current design was agreed during the redesign process. It uses currentColor to ensure 7:1 contrast in most situations. We also have an animation of the outline. The feedback from keyboard and low vision users has been positive so far, I don’t see an urgent reason to re-evaluate this decision.
