### ISSUE TITLE
Undefined method `find'

### ISSUE THREAD

**Issue by zwiastunsw** [w3c/wai-website#203]
I try to install wai-website-theme. I get an error
 
> jekyll 3.8.5 | Error:  undefined method `find' for "../_external/data/translations.yml":String

System: Windows 10, Ruby26-x64

**Comment by yatil** [comment]
Hi @zwiastunsw, please note that the theme is only to be used for resources that will be at https://w3.org/WAI.

The error relates to a missing data file, which we store in the wai-website-data repository which we embed using Git Submodules.
