### ISSUE TITLE
date format - code weight

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-website#214]
Background: [ATAG Report Tool in-progress-draft](https://atag-report-tool.hdv.now.sh/about) is using JavaScript, no library

The date format provided is ddd MMM DD YYYY (e.g., Fri Jun 05 2020).

We would like a different date format, per https://github.com/w3c/wai-website/issues/212

We do not want to add code weight for it, especially since this date that is a very minor aspect of the tool.

**_Question:_ Is there a light-weight way to get the date format we want with JavaScript?**

**Comment by hidde** [comment]
Looked into this a bit more, yes, there are date libraries that are ~1-2kb, we can do what we want with those. So it adds weight, but it is negligible.
