### ISSUE TITLE
Use of uppercase letters for link text in header

### ISSUE THREAD

**Issue by yatil** [w3c/wai-website#23]
_From @srinivasuchakravarthula on March 20, 2018 6:46_

As we normally don't recommend use of `<uppercase>` for things other than abbreviations, I think we should change link text of "Get Involved" and "About W3C WAI (ABOUT world)" to none. This improves readability. 

_Copied from original issue: w3c/wai-tutorials#550_

**Comment by slhenry** [comment]
Agree. We are making these mixed case.

**Comment by yatil** [comment]
Committed and can be previewed here:
https://w3c.github.io/wai-website/
