### ISSUE TITLE
Support for Windows 7 & IE 11 Combinations

### ISSUE THREAD

**Issue by HerinHentry** [w3c/wai-website#24]
Hi,

I used my old PC to check the site and few components look very distorted in IE 11+ Windows 7 combination. Chrome looks fine. Attached are the screenshots.

![image](https://user-images.githubusercontent.com/15111528/37765186-ac55d94a-2e17-11e8-9964-20b4f4810540.png)

![image](https://user-images.githubusercontent.com/15111528/37765211-bddee2ec-2e17-11e8-90b0-83c5fd697e24.png)

**Comment by yatil** [comment]
Hi @HerinHentry,

this is a [known issue](https://github.com/w3c/wai-website/wiki/W3C-WAI-Website-Redesign-Information) – I just ran out of time to adapt to IE11 (especially the homepage and navigation got a lot of changes since I tested the last time).

Thanks for the reminder :-)

**Comment by yatil** [comment]
Fixed a lot of inconsistencies today, I‘ll leave some screenshots here as a todo list for me to tackle next :-)

* [ ] ![image 2018-05-02 at 5 08 01 pm](https://user-images.githubusercontent.com/58862/39531787-4be2f93c-4e2c-11e8-89dd-6ebdd9eb53c7.png)
* [ ] ![image 2018-05-02 at 5 18 18 pm](https://user-images.githubusercontent.com/58862/39532270-d3fe82d2-4e2c-11e8-8242-4f0682492ef9.png)
* [ ] ![image 2018-05-02 at 5 21 53 pm](https://user-images.githubusercontent.com/58862/39532541-53314abc-4e2d-11e8-8474-3156a87d6705.png)
* [ ] ![image 2018-05-02 at 5 23 01 pm](https://user-images.githubusercontent.com/58862/39532633-7c3666fe-4e2d-11e8-95c8-2d50eae1a68a.png)
* [ ] ![image 2018-05-02 at 5 34 20 pm](https://user-images.githubusercontent.com/58862/39533341-15db7ee2-4e2f-11e8-9bf0-f15cb4fdbc5f.png)
* [ ] ![image 2018-05-02 at 5 50 01 pm](https://user-images.githubusercontent.com/58862/39534173-46751d7c-4e31-11e8-8a53-a8a7207a831f.png)


## Several things in the tips for getting started:

* [ ] ![image 2018-05-02 at 5 24 52 pm](https://user-images.githubusercontent.com/58862/39532762-be00f842-4e2d-11e8-8a5c-0dacef7bb436.png)
* [ ] ![image 2018-05-02 at 5 27 32 pm](https://user-images.githubusercontent.com/58862/39532954-21db5664-4e2e-11e8-94f6-83a6fb3d50b9.png)
* [ ] ![image 2018-05-02 at 5 28 26 pm](https://user-images.githubusercontent.com/58862/39533009-3e2f5d74-4e2e-11e8-9b50-87ea3a99943b.png)
* [ ]  ![image 2018-05-02 at 5 29 14 pm](https://user-images.githubusercontent.com/58862/39533043-609bf8cc-4e2e-11e8-97c4-440e1980399f.png)
* [ ]

**Comment by yatil** [comment]
I have addressed the ones above. There might be minor issues still, but let’s collect them in new issues as they come up :-)
