### ISSUE TITLE
[low] fix conflict (that doesn't seem to be causing problems)

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website#260]
1:21:30 PM:           Conflict: The following destination is shared by multiple files.
1:21:30 PM:                     The written file may end up with unexpected contents.
1:21:30 PM:                     /opt/build/repo/_site/fundamentals/accessibility-usability-inclusion/index.html
1:21:30 PM:                      - pages/fundamentals/accessibility-usability-inclusion.md
1:21:30 PM:                      - pages/fundamentals/wai-inclusion.md

**Comment by remibetin** [comment]
Old conflict. Fixed by https://github.com/w3c/wai-website/commit/c2eda9c3373c7f65a5411d37a08696a09ed1b698#diff-6d38d3cb57c69420193ebee169fa6b7130187827aacf02fc3b06b5e4fa956f78
