### ISSUE TITLE
Consistency of structure of content across pages - Summary

### ISSUE THREAD

**Issue by HerinHentry** [w3c/wai-website#27]
Hi,

Most of the pages including the https://www.w3.org/WAI/beta/fundamentals/components/ page contain a summary section before the Page content section.

But, this is not consistent across. The summary is missing in some of the pages.
https://www.w3.org/WAI/beta/people-use-web/tools-techniques/

Maybe this is intentional due to different templates. But, I think a small summary introduces the context of the page to the users. Just a recommendation.

Thanks,

**Comment by slhenry** [comment]
Thank you for the comment. We also got positive response to the Summaries during usability testing.

We will be adding summaries to most pages as we update them. Some will be done before the redesigned site is released (probably in May), and others will come later.
