### ISSUE TITLE
Use 简体中文 for Simplified Chinese (zh-hans)

### ISSUE THREAD

**Issue by xfq** [w3c/wai-website#277]
The WAI Website [currently uses 简体汉语 for Simplified Chinese translations](https://github.com/w3c/wai-website-theme/blob/fa2134961731f4e61a6c3fb47b3e4c2b72dc173b/_components/sidenav/languages.html#L10), but 简体中文 is more commonly used. See https://github.com/w3c/i18n-drafts/pull/330 for more details.

/cc @xueyuanjia @ruoxiran

**Comment by ruoxiran** [comment]
I submitted this [pull request](https://github.com/w3c/wai-website-data/pull/77) to fix this issue. 
hi, Shawn @shawna-slh, please help review whether I have updated the appropriate json file. Thank.

**Comment by shawna-slh** [comment]
Thank you. I hope to get to this soon. Feel free to ping me in a couple of days if I have not yet.

**Comment by shawna-slh** [comment]
Thanks for pull request! Published. Looks correct to me.
