### ISSUE TITLE
Skip to Content Link in Pages with "other pages in this resource" navigation

### ISSUE THREAD

**Issue by HerinHentry** [w3c/wai-website#28]
Hi,

I was expecting the Skip to content navigation to take me to the "actual content" area in this page.

https://www.w3.org/WAI/beta/about/#main

But, apparently, the "other pages in this resource" navigation is part of the main and hence keyboard focus transfers to this. I do not think this should be in the main content area.

![image](https://user-images.githubusercontent.com/15111528/37767675-08508680-2e1f-11e8-80be-790104a1e717.png)

Thanks,

**Comment by yatil** [comment]
We’ll revisit this once we made the changes in #34. I think the side navigation should be skipped – It also probably means that we need to have another look at where our `<main>` element is.
