### ISSUE TITLE
Perspective Videos -Broken links

### ISSUE THREAD

**Issue by HerinHentry** [w3c/wai-website#29]
Hi,

In this page, the links on the left-hand navigation seem to be fine. But, the ones below the images and the linked images take to the link https://www.w3.org/perspective-videos/keyboard/ resulting in 404 error.

https://www.w3.org/WAI/beta/perspective-videos/

Thanks

**Comment by yatil** [comment]
Fixed in https://github.com/w3c/wai-perspective-videos/commit/fe8767aeeb7c4d4c019b624d06f20421e90aabe2, https://github.com/w3c/wai-perspective-videos/commit/bd45c9c31877c0021e529db88f1685f6f004f5bf, and https://github.com/w3c/wai-website/commit/2b4239c753f794f4938d6caf8d8bf956a8899414.
