### ISSUE TITLE
Fix bad HTML in Accessibility Intro

### ISSUE THREAD

**Issue by yatil** [w3c/wai-website#3]
The change made yesterday introduced bad HTML to the Accessibility Intro page. As I went lengths to clean up bad HTML, that was present on most of the old pages, please provide proper HTML5.

https://validator.w3.org/nu/?doc=http%3A%2F%2Fw3c.github.io%2Fwai-website%2Ffundamentals%2Faccessibility-intro%2F

- Using acronym
- having a `shape="rect"` attribute on a elements

**Comment by slhenry** [comment]
Those things cleaned up. It's going through extensive revision, currently wants CSS work, and will need QA check -- later.
