### ISSUE TITLE
Youtube video - External link?

### ISSUE THREAD

**Issue by HerinHentry** [w3c/wai-website#30]
Hi,

In page https://www.w3.org/WAI/beta/perspective-videos/, there is a For presentations:  compilation of all 10 videos (7:36 minutes) link that takes to youtube.

I think it's a best practice to let the visual and screen reader users know it is an external link.

Current code:
`<a href="https://www.youtube.com/watch?v=3f31oufqFSM">compilation of all 10 videos (7:36
minutes)</a>`

Thanks

**Comment by yatil** [comment]
Fixed in https://github.com/w3c/wai-perspective-videos/commit/98daa9b8238475975f16679f752051392f3e1c5a and 0be2ab1a9c35143a2d119d2d3ac14e9773943221.
