### ISSUE TITLE
Setup branch protection for all resource repos

### ISSUE THREAD

**Issue by SteveALee** [w3c/wai-website#310]
For each - take the branch listed in [.gitmodules](https://github.com/w3c/wai-website/blob/master/.gitmodules) and 

- apply branch protections:
  - Require a pull request before merging 
  - Restrict who can push to matching branches
- check no one listed under collaborators and teams has > write access
 
- [x] wai-InvolveUsersAll
- [x] wai-InvolveUsersEval
- [x] wai-about-w3c-process
- [x] wai-about-wai
- [x] wai-accessibility-principles
- [x] wai-aria-practices
- [x] wai-arrm
- [x] wai-atag-report-tool
- [x] wai-audiences
- [x] wai-authoring-tools-list
- [x] wai-bcase
- [x] wai-cognitive
- [x] wai-combined-expertise
- [x] wai-components
- [x] wai-conformance-eval-overview
- [x] wai-contacting-orgs
- [x] wai-course-list
- [x] wai-curricula
- [x] wai-customize-design
- [x] wai-design-develop-overview
- [x] wai-develop-training
- [x] wai-easy-checks
- [x] wai-eval-overview
- [x] wai-eval-report-templates
- [x] wai-eval-standards
- [x] wai-eval-tools-overview
- [x] wai-evaluation-tools-list
- [x] wai-first-aid
- [x] wai-fundamentals-overview
- [x] wai-inclusion
- [x] wai-interactive-lists
- [x] wai-intro-accessibility
- [x] wai-intro-act
- [x] wai-intro-aria
- [x] wai-intro-atag
- [x] wai-intro-earl
- [x] wai-intro-linking
- [x] wai-intro-uaag
- [x] wai-intro-wcag
- [x] wai-media-guide
- [x] wai-mobile
- [x] wai-news
- [x] wai-older-users
- [x] wai-org-policies
- [x] wai-people-use-web
- [x] wai-people-use-web-videos
- [x] wai-personalization-standards
- [x] wai-perspective-videos
- [x] wai-plan-policies-overview
- [x] wai-planning-and-managing
- [x] wai-policies-prototype
- [x] wai-presentations2all
- [x] wai-pronunciation
- [x] wai-quick-start
- [x] wai-resource-list
- [x] wai-resource-template
- [x] wai-selecting-eval-tools
- [x] wai-shared-experiences
- [x] wai-sitemap
- [x] wai-statements
- [x] wai-std-gl-overview
- [x] wai-std-harmonization
- [x] wai-teach-advocate-overview
- [x] wai-tutorials
- [x] wai-video-standards-and-benefits
- [x] wai-wcag-em-overview
- [x] wai-wcag-em-report-tool
- [x] wai-wcag-mob-overlap
- [x] wai-wcag-supplemental
- [x] wai-wcag-understanding
- [x] wai-website
- [x] wai-website-data
- [ ] wai-website-deploy-test
- [x] wai-website-theme
- [x] wcag-act-rules

**Comment by SteveALee** [comment]
@shawna-slh are you aware of any I can leave out of above. 

I intend to leave ACT, APG and Curricular until after meeting

**Comment by SteveALee** [comment]
All done and tested with wcag-act-rules, wai-intro-wcag and wai-aria-practices

**Comment by shawna-slh** [comment]
Hey @SteveALee Please wait to do more until after we talk. Thanks!

**Comment by SteveALee** [comment]
Sure, though I think the new protected branch has been added to all repos now.
