### ISSUE TITLE
minimal header layout - logos in header

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website#316]
* [x] medium-high priority &mdash; remove link to w3.org
* [x] low-medium priority &mdash; decrease space between the logos; make it visually and programmatically one logo linked to w3.org/WAI/
* [ ] low priority &mdash; right-align

![image](https://user-images.githubusercontent.com/6991814/183522535-a7a0e5bf-cfd6-4276-a25f-789abcd93a28.png)

resources:
1. [Supplemental Guidance to WCAG 2](https://www.w3.org/WAI/WCAG2/supplemental/)
2. [WCAG 2 Test Rules](https://www.w3.org/WAI/standards-guidelines/act/rules/about/)
3. [ARIA APG](https://www.w3.org/WAI/ARIA/apg/)
4. **draft** [WCAG Techniques](https://draft-wcag-redesign.netlify.app/techniques/) and [Understanding](https://draft-wcag-redesign.netlify.app/understanding/)
5. [WCAG-EM Report Tool](https://www.w3.org/WAI/eval/report-tool/)
6. [ATAG Report Tool](https://www.w3.org/WAI/atag/report-tool/)

5 and 6 have the logos right aligned, which I prefer:
![image](https://user-images.githubusercontent.com/6991814/183522767-5c80fc95-fb2d-48df-8cba-b18e0a414b22.png)

others do not, e.g.:
![image](https://user-images.githubusercontent.com/6991814/183517659-073cb6a9-9a07-4a78-aedc-d77688e9ef4d.png)

**Comment by SteveALee** [comment]
Should we add facility to make the top left title a link as well?

**Comment by shawna-slh** [comment]
> Should we add facility to make the top left title a link as well?

Yes, please! Note that [ARIA APG](https://www.w3.org/WAI/ARIA/apg/) already did that. And please check what they did with semantics -- I think we want to do the same.

* [ ] Check?Update semantics
* [ ] Make first text linked to index page by default (yet optionally can be not linked)

**Comment by SteveALee** [comment]
W3C - WAI logo are both a single link now

**Comment by SteveALee** [comment]
@shawna-slh 
> 5 and 6 have the logos right aligned, which I prefer:

those two also have reduced width - do you also want that? I suspect the text won't easily fit. Also APG has a hero area that is full width which causes an issue.

**Comment by shawna-slh** [comment]
Thanks! As we discussed:
* [ ] need broader width for the supplemental guidance, APG, ACT Rules, and WCAG
* [ ] [lower priority] can you also combine the W3C and WAI logos for the main site?

**Comment by shawna-slh** [comment]
made fresh issue https://github.com/w3c/wai-website/issues/337
