### ISSUE TITLE
new wai/people page IA & navigation

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website#334]
**updated proposal is implemented in https://deploy-preview-83--wai-fundamentals-overview.netlify.app/fundamentals/**
In the left nav, the "Accessibility: It's About People" link expands, and the others don't work in the preview.

<hr>

currently IA is:
[Accessibility Fundamentals](https://www.w3.org/WAI/fundamentals/)
* [Introduction to Accessibility](https://www.w3.org/WAI/fundamentals/accessibility-intro/)
  * [Video Introduction](https://www.w3.org/WAI/videos/standards-and-benefits/) 
* [Digital Accessibility Courses](https://www.w3.org/WAI/courses/)
  * [W3C Foundations Online Course](https://www.w3.org/WAI/courses/foundations-course/)
  * [Course List](https://www.w3.org/WAI/courses/list/)
* [Components of Web Accessibility](https://www.w3.org/WAI/fundamentals/components/)
* [Accessibility Principles](https://www.w3.org/WAI/fundamentals/accessibility-principles/)
* [Perspectives Videos](https://www.w3.org/WAI/perspective-videos/)
* [How People with Disabilities Use the Web](https://www.w3.org/WAI/people-use-web/)
* [Older Users and Accessibility](https://www.w3.org/WAI/older-users/)
* [Accessibility, Usability, Inclusion](https://www.w3.org/WAI/fundamentals/accessibility-usability-inclusion/)

That's too much at the top level.

We're adding a new page (which is the endplate of the videos): [w3.org/WAI/people](https://www.w3.org/WAI/people/)
It could be a page with just the new videos on it.
Or, we can use it as a parent page and group related pages under it.

Option A, nav top-level:
[Accessibility Fundamentals](https://www.w3.org/WAI/fundamentals/)
* [Introduction to Accessibility](https://www.w3.org/WAI/fundamentals/accessibility-intro/)
* [Accessibility: It's About People](https://www.w3.org/WAI/people/)
* [Components of Web Accessibility](https://www.w3.org/WAI/fundamentals/components/)
* [Accessibility Principles](https://www.w3.org/WAI/fundamentals/accessibility-principles/)
* [Digital Accessibility Courses](https://www.w3.org/WAI/courses/)

Option A, the IA:
[Accessibility Fundamentals](https://www.w3.org/WAI/fundamentals/)
* [Introduction to Accessibility](https://www.w3.org/WAI/fundamentals/accessibility-intro/)
  * [Video Introduction](https://www.w3.org/WAI/videos/standards-and-benefits/) 
* [Accessibility: It's About People](https://www.w3.org/WAI/people/)
  * [Perspectives Videos](https://www.w3.org/WAI/perspective-videos/)
  * [How People with Disabilities Use the Web, Videos](https://www.w3.org/WAI/people-use-web/)
  * [Older Users and Accessibility](https://www.w3.org/WAI/older-users/)
  * [Accessibility, Usability, Inclusion](https://www.w3.org/WAI/fundamentals/accessibility-usability-inclusion/)
* [Components of Web Accessibility](https://www.w3.org/WAI/fundamentals/components/)
* [Accessibility Principles](https://www.w3.org/WAI/fundamentals/accessibility-principles/)
* [Digital Accessibility Courses](https://www.w3.org/WAI/courses/)
  * [W3C Foundations Online Course](https://www.w3.org/WAI/courses/foundations-course/)
  * [Course List](https://www.w3.org/WAI/courses/list/)

Option B... _not sure of a better approach than Option A right now :-)_

Nav wording options:
1. Accessibility: It's About People
2. Accessibility is About People
3. Understanding People
4. It's About People
5. People

**Comment by bakkenb** [comment]
+1 to the proposed Option A side navigation IA.
Still thinking about the best wording.

**Comment by remibetin** [comment]
@shawna-slh I guess we can close this issue?
- Option A has been implemented
- Another issue, https://github.com/w3c/wai-people-use-web/issues/324, adresses the evolution of this navigation.
