### ISSUE TITLE
default breadcrumb

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website#336]
can we set it to something generic?

currently it is Cognitive... Here in March 2022
![image](https://user-images.githubusercontent.com/6991814/209045297-4f60f63a-422e-4e76-b573-a94e3bcda415.png)

**Comment by remibetin** [comment]
@shawna-slh Is this issue still relevant? Or can we close it?

**Comment by shawna-slh** [comment]
If it's not solved, it's still an issue. I think you/we solved it; however, I don't remember. :(
