### ISSUE TITLE
Fix Copyright

### ISSUE THREAD

**Issue by jnurthen** [w3c/wai-website#339]
currently states Copyright © 2023 W3C ® ([MIT](https://www.csail.mit.edu/), [ERCIM](https://www.ercim.eu/), [Keio](https://www.keio.ac.jp/), [Beihang](https://ev.buaa.edu.cn/)) [Permission to Use WAI Material](https://www.w3.org/WAI/about/using-wai-material/).

This is no longer correct and should be fixed by Feb 1 according to pubrules for specs. I assume similar applies for web sites - see https://www.w3.org/pubrules/doc/rules/?profile=WD#copyright

**Comment by shawna-slh** [comment]
Yup. It's on my To Do list. :)

**Comment by Travisnarkle79** [comment]
> currently states Copyright © 2023 W3C ® ([MIT](https://www.csail.mit.edu/), [ERCIM](https://www.ercim.eu/), [Keio](https://www.keio.ac.jp/), [Beihang](https://ev.buaa.edu.cn/)) [Permission to Use WAI Material](https://www.w3.org/WAI/about/using-wai-material/).
> 
> This is no longer correct and should be fixed by Feb 1 according to pubrules for specs. I assume similar applies for web sites - see https://www.w3.org/pubrules/doc/rules/?profile=WD#copyright

**Comment by shawna-slh** [comment]
Please refresh and then let me know on which page you are seeing that old copyright?

I'm only getting the updated version customized for the WAI sub-site situation:
> Copyright © 2023 World Wide Web Consortium ([W3C](https://www.w3.org/)®). See [Permission to Use WAI Material](https://www.w3.org/WAI/about/using-wai-material/).
