### ISSUE TITLE
w3c/wai/you panels

### ISSUE THREAD

**Issue by brewerj** [w3c/wai-website#35]
Good to see the design stabilizing nicely. As it has evolved, I note that the w3c/wai/you panels are reduced in size, but for some viewers still take up the majority of initial visual real estate; but that they don't seem to have a commensurate functional value, especially given that they are not interactive. The messages in these panels seem informative in a way that would be most useful for first time visitors, but would reduce in value for repeat visitors. Also, they are confusing because (visually) they appear clickable, but aren't. There is lots of useful information below them, but visual viewers may need to scroll down to discover that, and they might not be tempted to do so. 

My understanding is that the plan is to shrink these further by combining the three panels/boxes into one panel/box to give less of an appearance of clickable areas. This may not solve the problem and it could create a new one. A combined horizontal box spanning the page could, for visual viewers, block the visual flow down the page, making it less likely for those viewers to explore "below the fold." And the apparent "clickability" of the panels may be driven more by the borders of the boxes than by the number of the boxes. 

Here are a few suggested minimalist tweaks towards finalizing the centerpiece of the home page, given that the site is nearly done: 
- Currently each of the panels has padding that could be tightened up, including white space inside of the borders around the embedded images and text, plus white space outside of each panel. Reducing the padding would allow us to reduce the depth of these panels -- potentially by as much as half -- and could encourage more people to explore below the panels. 
- The apparent "clickability" of the panels may be due to the borders for each panel. What about simply removing the border around each of those three panels? For people who are perceiving the website visually, their eye can more easily pass through these areas and flow down to the information below.

**Comment by yatil** [comment]
I try to recall what we did at the F2F that pleased us, @slhenry…

* We played with the alignment of the “headings” in that area and didn’t like it left aligned.
* I think we agreed to try out to remove the thick borders, I think, and replace them with finer lines or just have a box around all three items.

I don’t think we came to a conclusion, hence the lack of notes on my end, as far as I recall.

I played a bit with the elements section, as a start, so we have something to look at:
<img width="1362" alt="smaller images, less space, remove redundant text" src="https://user-images.githubusercontent.com/58862/38935630-19103186-431f-11e8-9db9-9bd346234009.png">

**Comment by yatil** [comment]
Some iterations on this:

<img width="1680" alt="image 2018-04-18 at 6 41 55 pm" src="https://user-images.githubusercontent.com/58862/38946123-cfa583b0-4338-11e8-8872-2a67b979077c.png">
<img width="748" alt="image 2018-04-18 at 6 42 43 pm" src="https://user-images.githubusercontent.com/58862/38946125-d2dc534c-4338-11e8-8adb-6621b74e6695.png">
<img width="420" alt="image 2018-04-18 at 6 44 37 pm" src="https://user-images.githubusercontent.com/58862/38946132-d5323a80-4338-11e8-84f5-33d252bea5af.png">
<img width="410" alt="image 2018-04-18 at 6 44 46 pm" src="https://user-images.githubusercontent.com/58862/38946133-d6cd1da6-4338-11e8-880e-de656b800e2c.png">
<img width="1316" alt="image 2018-04-18 at 6 37 49 pm" src="https://user-images.githubusercontent.com/58862/38946136-daab2012-4338-11e8-92ca-f6a6fe171d35.png">

**Comment by yatil** [comment]
@brewerj Ha, I was just dropping them in here as a reminder for me and Shawn. I hope to get to implementation tomorrow and thwn I’ll post the preview here :-) Good that you like the iteration.

**Comment by yatil** [comment]
> [By the way, grammatically, in this usage of "provides," a "with" is needed, e.g. "W3C WAI provides you with strategies..."]

I added the “with” for now, but I wonder if we can wordsmith that sentence in the future. Currently, I read the sentence and think “who provides what to whom to do what exactly” :-) It reads more complicated than it probably needs to be.

**Comment by yatil** [comment]
The preview is now available here: https://w3c.github.io/wai-website/

**Comment by slhenry** [comment]
(Agree "provides you with" made it even more awkward. I deleted that part of the phrase all together. I think it's clear enough form the text underneath.)

Redesign addressed other issues.
Closing this issue.
Re-open if needed.

**Comment by brewerj** [comment]
Commenting on the updated panels, the appearance-of-clickability issue seems pretty well resolved with the tweaked design in the preview noted above. Thanks.

I think that there is still an issue of excess non-interactive vertical space due to the w3c/wai/you panel, even given the tweaks. It would be great to keep the panel, given the nice icons and useful text for first-time visitors, while getting people to the interactive content below that a little quicker, visually. 

The simplest and most effective way to do this might be to shrink the padding inside the bottom of that panel just a little bit, and to shrink the padding above the "News" and "Get Resources For" by a corresponding little bit. Right now there's a double dose of non-interactive vertical padding between the panel and the next round of interactive content. 

And by the way, I think that the beta version hangs together better overall with the consolidation of font treatments on the page since I last viewed it, even within a single font family. Thanks.

**Comment by yatil** [comment]
I’d rather not remove more padding from the component as it means we have different paddings in different sections and also means that the initial impression is even denser. 

We had a design where we had “interactive content” == resources front and center at the top and couldn’t get sign off because we needed to explain what WAI and W3C are first. Now we seem to be swinging the pendulum into the other direction.

I’d say keep as is and see what changes we want to make once we have the site up and running.

**Comment by yatil** [comment]
- [ ] remove bottom margin from p elements
- [ ] remove top margin from h2 elements in teasers

**Comment by slhenry** [comment]
and that gives us 32 pixels :)

**Comment by brewerj** [comment]
With regard to consistency of paddings in different sections, I doubt that that matters as much when one is scrolling vertically through the current page design, as does amount of non-interactive space before one gets to interactive content. But if you want to keep the padding consistent, you could reduce the padding currently around the "see all news" button (particularly after) -- as it currently seems to float un-anchored, and not be at any risk of appearing "dense." 

To be clear though, my concern is more functional than aesthetic -- that we may lose some readers due to the screen space taken by non-interactive panels, before they get themselves to the interactive content. 
 
I don't believe that this is a case of swinging the pendulum back in the other direction, as you suggest above, because I think that the W3C/WAI/You panel info is good and I've specifically suggested above that we be sure to keep it. I am however suggesting that we refine how we present it, so as not to introduce a second problem while resolving the first one. How about giving that a try and seeing how it works?

**Comment by yatil** [comment]
@brewerj Shawn and I already agreed on an approach, see above.

**Comment by brewerj** [comment]
Non-urgent follow-up thought: 
* The margin tweaks for p and h2 work well to tighten up the w3c/wai/you panel;
* There is a similar issue of extended vertical space lower down on the page, after the end of the News and before the "See all News" button; then again after the "See all News" button and before the "Sponsors & Funders." Could you apply a similar approach to tighten up the empty vertical space at those transitions, to tie that content in with the rest of the page more?

**Comment by yatil** [comment]
@brewerj I have created a new issue (#58) with your feedback. Please note that no-one will be pinged when you comment on closed issues, so comments are likely overlooked. It’s always better to open a new issue.
