### ISSUE TITLE
Proliferation of fonts and font sizes, styles and weights

### ISSUE THREAD

**Issue by brewerj** [w3c/wai-website#36]
This is more of an observation than a request. I noticed that on the current WAI Beta site, there appear to be several different fonts in use, and multiple font sizes, cases, styles and weights. My guess is that there are good usability rationales for every one of these choices. Nevertheless, this proliferation probably loses a bit with regard to the overall visual coherence of the website. 

My suggestion is to do a (very) quick check of font size/style/weight choices before finalizing the website, just to see if it would make sense to consolidate a few of the size, style and weight choices. My guess is that it might help tie together the visual appearance of the website more strongly. 

To be clear, I think it's OK to go ahead with these font choices, and that this is a minor issue. I'm just suggesting being mindful of this observation, and where possible re-using existing font choices and consolidating if & where possible, before adding any more.

**Comment by yatil** [comment]
Hi @brewerj,

the website only uses Noto Sans as the font, there should be no other fonts around (apart from a mono-spaced one). If you find other fonts, can you report them with screenshots and URLs so we can see if it is a CSS problem, a font not loading or a display issue that is local to your machine?

I know @slhenry has a few font-size & style things that we want to address before launch, and then we’ll see in practice if there is something that feels wrong.

Thanks for the feedback.

**Comment by brewerj** [comment]
There's actually already another font family present because of the textual logo, which is not in itself a problem, but something to bear in mind when considering the amount of variation of in fonts. These include sizes (maybe five different sizes, across a wide range), styles (italic, underline), weights (regular, bold) and cases (all caps, initial caps) for the primary font, Noto Sans. So even though they are technically within the same font family, it is more to process visually. 

Again I do not see this as a major issue, but wanted to clarify my comment and suggest it as something to be aware of, in case you have opportunities to consolidate font options rather than further proliferate them as you're finalizing the design, otherwise for future reference. Thanks.

**Comment by slhenry** [comment]
Top banner / nav  changes at <https://user-images.githubusercontent.com/58862/38721866-27d58044-3efc-11e8-9833-59ed14f30951.png> have fewer font treatments.

In the W3C, WAI, You block revision at <https://github.com/w3c/wai-website/issues/35#issuecomment-38245341>, we've changed to font treatments that are throughout the rest of the page.

These have significantly decreased the variations throughout the home page, and the site.

Closing this issue for now.
Feel free to reopen if suggest other places to consider simplifying font treatments.
