### ISSUE TITLE
are all included in search?

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website#361]
https://github.com/w3c/wai-website/blob/e6be3d050898fa9930077f4580d0e6b73e6962d6/_config.yml#L361

tipue_search:

**Comment by remibetin** [comment]
@shawna-slh Yes: all pages, posts and collections are included in search.

The only excluded pages are those listed here: https://github.com/w3c/wai-website/blob/cafcf7b77ca5df6400c6ff7f550aaa63544a2407/_config.yml#L343-L358

Is this ok with you?
