### ISSUE TITLE
[med][search] search history auto-suggest

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-website#4]
Understand issues and what we want to do with clearing it and/or auto-populating it -- or disabling it.

(some surprising stuff in there already)

**Comment by yatil** [comment]
We have no autosuggestion enabled as far as I’m aware of (and I should know :-D). Your browser might give you suggestions based on your personal search history. – A screenshot would be good to verify.

**Comment by slhenry** [comment]
<img width="241" alt="search-autofill" src="https://user-images.githubusercontent.com/6991814/37402404-6c71d3b6-2759-11e8-958a-ee61078c9959.png">

**Comment by yatil** [comment]
That’s your personal search history. Works as designed! :-) (We can switch it off, but I would expect it.)
