### ISSUE TITLE
Fix nav & intro pages for EARL & ACT

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-website#40]

**Comment by slhenry** [comment]
(and remember to add summary and footers)

**Comment by yatil** [comment]
@slhenry Unsure what I need to do. Trying to piecing it together…

- [ ] Add parent page https://github.com/w3c/wai-eval-standards/blob/master/index.md to the navigation. where EARL & ACT currently is.
- [ ] Add the current EARL & ACT page as a sub-menu item to this parent page. (https://github.com/w3c/wai-intro-earl/blob/master/index.md)
- [ ] Rename that page to EARL in the navigation.
- [ ] Add the new ACT page as a sub-menu item to the parent page.
