### ISSUE TITLE
DL: Less left indentation and DT: Elements strong

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-website#42]
I think we want &lt;dd&gt;s to have less indent. Here's what I'm seeing now:
![dl-hang-new](https://user-images.githubusercontent.com/6991814/39190610-8afdb94c-479a-11e8-8252-9494317e39c2.png)

compare to current site - which works better for some people low vision and some cognitive abilities:
![dl-hang-now](https://user-images.githubusercontent.com/6991814/39190886-2a403b56-479b-11e8-9216-6799f4a633d2.png)

Also, I think we want our default style is &lt;dt&gt;s are bold. (I think that's in another issue somewhere?)

**Comment by yatil** [comment]
* Reason for indentation: It is in our grid. Happy to change
* Reason for non-bold DT: We sometimes use bolding in DTs or have used bold text in DTs in the past. When we use bold font for DT by default, we lose the possibility to do that. Happy to change.

**Comment by slhenry** [comment]
> Reason for indentation: It is in our grid. Happy to change

Yes, please. :)

> When we use bold font for DT by default, we lose the possibility to do that.

um - can't we override it? I think we want *most* DTs to be bold. Therefore, I think we want bold the default in the main CSS. Agree that we might want some DTs not bold. Let's discuss if needed.

**Comment by slhenry** [comment]
Consider spacing. Probably add class for more space between items...

**Comment by yatil** [comment]
> um - can't we override it? I think we want most DTs to be bold. Therefore, I think we want bold the default in the main CSS. Agree that we might want some DTs not bold. Let's discuss if needed.

It’s easier and more semantic to say `<dt><strong>This is a dt that should be strong</strong></dt>` instead of having a class that says `<dt class="thisdtisnotthatimportant"></dt>`. However, no need for discussion.

> Consider spacing.  Probably add class for more space between items...

Spacing was considered. I don’t want to add too many styles for fringe use cases because it clutters our CSS and we have to constantly look it up.

Please tell me what space you want around what or point me to a page where you like the spacing and all variants and I’ll put that into our styleguide.

**Comment by yatil** [comment]
Uh, I should have looked at your first screenshot where the `<dt>`s actually **are bold**. 
* See also our style guide that is used: https://w3c.github.io/wai-website-components/components/detail/list-description-list.html 
* Here in the rendering it is bold, too: https://w3c.github.io/wai-audiences/audiences/users/
