### ISSUE TITLE
Wrong European Institution

### ISSUE THREAD

**Issue by 3l3gant-cod3s** [w3c/wai-website#453]
Hi,
European Directives (~Laws) are adopted by the European Parliament and the Council of the European Union (aka The Council or the Council of Ministers), by codecision, or by the European Commission:
The European Accessibility Act was adopted thru the ordinary legislative procedure, thus not by the Commission.
https://en.wikipedia.org/wiki/European_Union_legislative_procedure#Ordinary_legislative_procedure
https://en.wikipedia.org/wiki/European_Accessibility_Act#References
**Directive (EU) 2019/882 of the European Parliament and of the Council** of 17 April 2019 on the accessibility requirements for products and services ELI http://data.europa.eu/eli/dir/2019/882/oj
Instead of "**The European Commission adopted** the European Accessibility Act, requiring ATMs and […]"
in https://www.w3.org/WAI/business-case/#minimize-legal-risk it must be:
"The **European Parliament and the Council adopted** the European Accessibility Act, requiring ATMs and […]"
"The **European Union adopted** the European Accessibility Act, requiring ATMs and […]" is exact but less precise.
Thank you.

**Comment by remibetin** [comment]
@3l3gant-cod3s Thanks for raising this issue.

I would go for “**The European Union** adopted the European Accessibility Act”. 
“**The European Parliament and the Counci**l adopted” may be more precise, but:
- this extra information does not provide additional meaning to the resource;
- it sounds too legal to me for an educational resource.

cc @shawna-slh

**Comment by 3l3gant-cod3s** [comment]
the correction was about the role of the European Commission, so… it looks perfect to me this way.
Thanks Rémi.

**Comment by remibetin** [comment]
Hi @sharronrush,

Would you be ok with this change?

> “The <ins>European Union</ins> adopted the European Accessibility Act, requiring ATMs and banking services, PCs, telephones and TV equipment, telephony and audiovisual services, transport, e-books, and e-commerce meet accessibility requirements.”

cc @shawna-slh

**Comment by sharronrush** [comment]
@remibetin Yes, I am ok with the change, thank you for that.

**Comment by remibetin** [comment]
@3l3gant-cod3s I have merged the related PRs. We will publish the new English & French versions today.

Feel free to reach out if you think the French translation can be improved. Thanks again!
