### ISSUE TITLE
anchor tag url seems to be changed for "The RESPECT Code of Practice"

### ISSUE THREAD

**Issue by bappyasif** [w3c/wai-website#485]
when clicking on that "anchor" tag, it takes to some other "url" than its supposed to!!

currently its taking to some "betting" site!!

**Comment by remibetin** [comment]
Thanks @bappyasif we have fixed the link and used an archived version for now.

The resolution context is at https://github.com/w3c/wai-website/pull/848

The updated page is at https://www.w3.org/WAI/planning/involving-users/
