### ISSUE TITLE
Header links

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-website#5]
W3C logo should go to w3.org

"Web Accessibility Initiative WAI" should go to w3.org/wai/

**Comment by yatil** [comment]
I disagree. That would even be an accessibility issue in my eyes. It’s W3C/WAI logo. When I’m on the website of W3C/WAI I expect that the complete logo goes to the homepage of the website, not to some other page.

Also, this would be a major rewrite of the header CSS.

**Comment by slhenry** [comment]
Existing website has 2 links: to W3C home page and WAI home page. That works well.

In current beta, I hover over "Web Accessibility Initiative WAI", it gets underlines and changes color... but when I click on it, it goes to w3.org
I don't understand why this wouldn't go to w3.org/wai/

**Comment by yatil** [comment]
It’s supposed to go to w3.org/WAI (respective w3.org/wai/beta for now.) That’s a bug.

**Comment by yatil** [comment]
Fixed in [this commit](https://github.com/w3c/wai-website-theme/commit/e45678da9b6b6c78ef398ec0c56a3410012aaf85). (I need to update the wai-website repository and upload to w3.org).
