### ISSUE TITLE
[minor] Header: tweak header separator lines contrast

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-website#51]
Current iteration has very low contrast (1.8:1) lines separating the main nav items.
And high contrast (7.1:1) separating lines in the top area (before tagline and between Get Involved and About WAI).

I think we want both to be about 4.5:1 (or possibly 3:1).

I'm happy to help figure that out when we get to it...

**Comment by slhenry** [comment]
Well, I'd call them helpful for visual separation, which aids perception and understanding.

However, I think they're OK in the main nav.

I still think they're a little too bright in the top nav. But agree we didn't come up with a good solution when looking at it the other day.

I said then that I thought the yellow would be too much... but I just tried it -- and actually, I like it. (we should have tried it the other day. ;-/) All those things are related directly to "WAI" so it'a nice to have the connection through the same yellow -- and good to get a tiny bit more color in...

![header-top](https://user-images.githubusercontent.com/6991814/39579650-e222de96-4eac-11e8-8ee9-699c6884af92.png)

**Comment by yatil** [comment]
So… go for the yellow then? Let me know.

**Comment by slhenry** [comment]
yea, please, thanks!
