### ISSUE TITLE
Help improve this page box edits

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website#525]
### Resource URL

most

### Add a description

Current text:
> Please share your ideas, suggestions, or comments via e-mail to the publicly-archived list [wai-eo-editors@w3.org](mailto:wai-eo-editors@w3.org?subject=...) or via GitHub

edits:
* change the default e-mail address to wai@w3.org
* change "via e-mail to the publicly-archived list" -> "via e-mail to"

Let me know if any questions or suggestion!

**Comment by remibetin** [comment]
@shawna-slh Some resources use a publicly-archived e-mail address to receive feedback:

- public-wcag-act@w3.org
- public-cognitive-a11y-tf@w3.org

What about including a special case to display "via e-mail to the publicly-archived list" when this is the case? For example, when a W3C email-address starts with "public-".

Other impacts:
- When the user clicks on the "E-mail" button in the feedback box, the email template currently includes "I give permission to share this to a publicly-archived e-mail list." I assume we also want to remove that when the mailing list is not publicly-archived.
- The current UI terms have been translated in many languages. We need to figure out how to update them. I will make a suggestion once we have clarified the above points.

**Comment by shawna-slh** [comment]
Thanks @remibetin ! I didn't think about all those implications.
For now, please just change the default e-mail address to [wai@w3.org](mailto:wai@w3.org)
Then you can close this issue. We will revisit it later if/when it becomes a priority.

**Comment by remibetin** [comment]
@shawna-slh Done
