### ISSUE TITLE
Laws & Policies Bread Crumb bug

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-website#53]
Reporting bug...

When I navigate into the Laws and Policies resource, and then go into one of the country pages, the breadcrumb breaks. It shows "Home - Standards/Guidelines - Referencing and Linking to Standards" instead of "Home - Laws and Policies = Canada"

**Comment by yatil** [comment]
Hi @bakkenb, I fixed it: https://w3c.github.io/wai-website/policies/canada/

The breadcrumb now correctly says:

> Home / Planning & Policies / Web Accessibility Laws & Policies / Canada
