### ISSUE TITLE
[minor] Fix Help improve this page on Writing Tips page

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-website#54]
On https://www.w3.org/WAI/beta/tips/writing/
the "Help improve this page" box is the full width. Not sure if that's a bug or a feature. ;-)

Also, please QA the previous & next on those Tips pages -- it doesn't seem right, but I didn't investigate.

(fyi, I think it's fine to leave off previous & next in those pages.)

**Comment by slhenry** [comment]
Just noticed it's also wide on https://w3c.github.io/wai-website/planning-and-managing/initiate/

**Comment by yatil** [comment]
The markup on the writing page is broken…

**Comment by yatil** [comment]
Fixed.
