### ISSUE TITLE
News spacing

### ISSUE THREAD

**Issue by yatil** [w3c/wai-website#58]
Reported by @brewerj in #35:

> Non-urgent follow-up thought:
> 
> The margin tweaks for p and h2 work well to tighten up the w3c/wai/you panel;
There is a similar issue of extended vertical space lower down on the page, after the end of the News and before the "See all News" button; then again after the "See all News" button and before the "Sponsors & Funders." Could you apply a similar approach to tighten up the empty vertical space at those transitions, to tie that content in with the rest of the page more?

**Comment by slhenry** [comment]
@brewerj , this is done.
