### ISSUE TITLE
Fix Archive link in footer

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-website#59]

**Comment by yatil** [comment]
Where is the resource? Where do I link to? What’s the URL? Did we forget about that? I’m unsure… ¯\_(ツ)_/¯

**Comment by slhenry** [comment]
From airtable:
> Not separate page. Section of sitemap. see also https://github.com/w3c/wai-sitemap/issues/2

**Comment by yatil** [comment]
So that would be `/sitemap/#archive`. Thanks!
