### ISSUE TITLE
change EOWG to a closed group

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website#590]
### Resource URL

https://www.w3.org/WAI/about/groups/

### Description
After the ducks are aligned:

* [x] update the main page to say it's closed
* [x] list as a closed group
* [x] remove from main navigation
* [ ] ...

**Comment by remibetin** [comment]
@shawna-slh I am closing this issue that is redundant with https://github.com/w3c/wai-website/issues/893 and was addressed by https://github.com/w3c/wai-website/pull/895 and https://github.com/w3c/wai-website/pull/920

Please let me know if something else is needed.
