### ISSUE TITLE
Consultancy

### ISSUE THREAD

**Issue by Santiagonu101** [w3c/wai-website#596]
### Resource URL

https://www.w3.org/WAI/fundamentals/

### Description

Hello, I would like to get some advice for my website about Accessibility Statement.

### Resource Shortname

wai-fundamentals

**Comment by shawna-slh** [comment]
Hello @Santiagonu101 

For guidance on accessibility statements, see: [Developing an Accessibility Statement](https://www.w3.org/WAI/planning/statements/)

W3C does not provide consulting services.
