### ISSUE TITLE
site map

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-website#6]
Needs WAI and WG info.

Also Contents.

draft at https://w3c.github.io/wai-sitemap/

**Comment by yatil** [comment]
Duplicate https://github.com/w3c/wai-sitemap/issues/2

**Comment by slhenry** [comment]
I think we need the WAI info asap. I am sure that some people will be disconcerted if the Working Groups and such are not on the site map when we announce beta.

**Comment by yatil** [comment]
Yes. We need that and I add that. It’s covered in https://github.com/w3c/wai-sitemap/issues/2. I just want to minimize having the same issues open in multiple places.
