### ISSUE TITLE
[very low priority!] ability to exclude a heading from the TOC

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-website#60]
For an auto-generated TOC, allow a specific heading to be excluded.

**Comment by yatil** [comment]
You can already do that. In Markdown on the next line write `{:.no_toc}` in the next line of the heading, and it is excluded. (I am going to add it to w3c/wai-develop-training in a second as an example.)

**Comment by yatil** [comment]
See here for example: https://github.com/w3c/wai-develop-training/commit/cc8ac6b01fecc86699843071fda61b397dbf8f9d
