### ISSUE TITLE
Too many headings

### ISSUE THREAD

**Issue by LJWatson** [w3c/wai-website#63]
Using a heading to represent the WAI mission statement and another to represent the name of the W3C, immediately under an invisible h1 at the start of the content area, doesn't set a good example.

Suggest making the h1 visible (so it can be used by everyone), and removing the h2 and h3 elements from around the subsequent pieces of text.

**Comment by yatil** [comment]
@slhenry What do you think? We had the mission statement at `<h1>` before and got different feedback. I can see both sides. (I personally think the `<h3>`s should stay – and become `<h2>`s when the heading changes – as I feel it is visually and semantically different sections of content.)

**Comment by slhenry** [comment]
I strongly agree that "Making the Web Accessible" and tagline ("mission statement") should not be h1.

h1 should be "W3C Web Accessibility Initiative (WAI) Home" and I think given all considerations, it does not need to be visible.

I also wonder if the h1 should be the first thing -- before the nav, etc. (Not on all pages, but just on this home page.)

h2 should be only "Making the Web Accessible". The heading should *not* include "Strategies, standards, and supporting resources to help you make the Web more accessible to people with disabilities." -- that's content after the heading.

While visually W3C, WAI, You are heading-like -- semantically, they're more like <dt>s in a <dl>... That would also help de-emphasize that section for repeat users.

However, I imagine that would take quite a bit of re-coding, so I think it's acceptable for now to go with:

h1> W3C Web Accessibility Initiative (WAI) Home
   h2> Making the Web Accessible
      h3> W3C
      h3> WAI
      h3> You
   h2> News
…

I think taking ""Strategies, standards, ..." out of the heading will help with Léonie's original issue sufficiently.

Happy to discuss...

**Comment by yatil** [comment]
> I also wonder if the h1 should be the first thing -- before the nav, etc. (Not on all pages, but just on this home page.)

We should not change the template on the home page. the H1 should be the entry point for the <main> element on all pages, consistently.

> h2 should be only "Making the Web Accessible". The heading should not include "Strategies, standards, and supporting resources to help you make the Web more accessible to people with disabilities." -- that's content after the heading.

OK, can create a separate style for just this instance of a subheading.

> I think taking "Strategies, standards, ..." out of the heading will help with Léonie's original issue sufficiently.

Good for me.
