### ISSUE TITLE
Responsive view causing truncation and text overflow at some screen widths.

### ISSUE THREAD

**Issue by grahamarmfield** [w3c/wai-website#64]
Liking the new design, but I think that some tweaking of breakpoints may be required for some aspects.

If you look at this screenshot from the Home Page at 720px screen width, you can see truncation and overflow of some elements of the unordered list in the Resources for... section.

I think at this screen width, the unordered list should be in just one column.
![new-w3c-screenshot-01](https://user-images.githubusercontent.com/2565505/39588686-2cb78ece-4ef4-11e8-9e6d-725ea63dd7d9.gif)

This was in Chrome 66 on Windows 10.

**Comment by slhenry** [comment]
We're changing the slashes (/) to commas. Even easier readability. :-)

**Comment by yatil** [comment]
Addressed (**not** live on https://w3.org/WAI/beta/ yet, preview at https://w3c.github.io/wai-website/
