### ISSUE TITLE
breadcrumb spacing

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-website#65]
I think we want space after the / 
(I thought it was there before but now is gone  ¯\_(ツ)_/¯

<img width="421" alt="breadcrumb" src="https://user-images.githubusercontent.com/6991814/39592460-6c8cabe2-4ecc-11e8-9f2a-762381e411f1.png">

**Comment by yatil** [comment]
Already fixed with this commit https://github.com/w3c/wai-website-components/commit/f967bcf967fdb250b6abbd9be89e2ea9ada69701#diff-c597f53dde73fb733a46af302d7fb1bd
