### ISSUE TITLE
About WAI - fix nav and breadcrumbs

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-website#67]
https://w3c.github.io/wai-website/about/

Let's talk as needed on order of items, etc.

**Comment by yatil** [comment]
Uh, that’s a really in-depth bug in the navigation. I have changed the code to allow for proper breadcrumbs.

**Comment by yatil** [comment]
The reason is that I forgot to properly configure the resource :-) I also found another CSS bug. Those changes are incoming…
