### ISSUE TITLE
Main menu visibility at different breakpoints

### ISSUE THREAD

**Issue by detlevhfischer** [w3c/wai-website#68]
When zooming into the page with browser zoom (triggering the moble breakpoint) and showing and then hiding the menu via the hamburger (menu) button, then zooming out again the main menu remains invisible at intermediate breakpoints where the menu (hamburger) is already hidden. The menu only reappears when zoomed out entirely or choosing a very wide browser viewport.  So something may need fixing about the breakpoints / menu vsibility.

**Comment by yatil** [comment]
I applied a stop-gap fix, however, this needs some work still:

- [ ] IE fix breaks responsiveness of logo area on mobile
- [ ] Menu button only triggers sub-menu on medium screens. (The main menu is always visible). Certainly not really what you want.

**Comment by yatil** [comment]
It now works quite OK, I’ve opened #76 for more improvements at a later date.
