### ISSUE TITLE
Reading level - Conform or Conformance

### ISSUE THREAD

**Issue by ChrisInTheWeb** [w3c/wai-website#7]
When I first came to the idea of web accessibility and 'readability' I was gobsmacked to see the use of the term 'conformance'. This audience includes people reading English as a second language and those requiring readability levels lower than academic. I suggest the w3c WAI retires the term conformance in favour of:

- conform
- to conform
- conformed

I say this imagining that the term 'comply' was not used as an active choice previously and that the same considerations may apply now.
 
Rgds,

Chris.

**Comment by yatil** [comment]
Hi @ChrisInTheWeb,

I think it is a good point and we might want to put it into our [editorial style guide for educational resources](https://www.w3.org/WAI/EO/wiki/Style), especially when writing active texts. However, “conformance” is a principle in close relation with WCAG, so it might come up from time to time.

Thanks for your feedback.

FYI @slhenry & @michael-n-cooper

**Comment by slhenry** [comment]
Thank you for the input.

I've added info on "conformance" to our Style Guide [Specific words](https://www.w3.org/WAI/EO/wiki/Style#Specific_words).

We are currently revising many of our resources to simplify the language. We will look for appropriate ways to avoid or define "conformance".

"Conformance" is an established term in some contexts, and we are not able to change it there now. In future work, we can consider different wording.
