### ISSUE TITLE
Moore advanced skip to than simple link

### ISSUE THREAD

**Issue by jongund** [w3c/wai-website#70]
Was a more advanced skip to feature for keyboard only users based on page landmarks and heading structure considered, for example the something like the PayPal Skipto.js utility?

The PayPal SkipTo.js provides a much more robust way for keyboard only users to navigate the content of a page than a simple link to main and it also provides a functional way for everyone to see the structural organization of the page (e.g. an outline).  

http://paypal.github.io/skipto/ 

Isn't the simple skipto link kind of out of date in the modern era of web development?

Jon

**Comment by yatil** [comment]
Hi @jongund, thanks for the feedback. I feel that such a solution would be too much for most users at this point. Users can use plugins that allow them to navigate to headings/landmarks on all pages, not just on our site, which is a more consistent user experience. Also, this particular solution provides no skip link at all in case JavaScript is not available (bad connection, user preference, content blocking). Our simple solution seems more roboust.

**Comment by yatil** [comment]
@slhenry and I talked about this and we agree to keep it lean for now, but open to discuss other navigation option in the future.
