### ISSUE TITLE
ability to collapse "Making the Web Accessible" panel in mobile

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-website#73]
Eric - I think we talked about this but didn't add an issue. I think it's in your head, so I'm not trying for a description. If need more info, we can discuss when we talk. :-)

**Comment by yatil** [comment]
@slhenry Thanks for noting. It’s still on the todo list but way down.

**Comment by yatil** [comment]
I just had a look and while the functionality is relatively easy to do, the document structure needs to be adapted for it to work (positioning, the relationship to the content, make sure it works in all browsers, has a proper accessible name).

One thing I also struggle with is how it looks when the area is hidden is that we have a huge button on the page that says “Show Making the Web Accessible section” or “Hide Making the Web Accessible section”. It’s quite bad for the visual design of the site and that for a region that is easy to skip by scrolling…

**Comment by yatil** [comment]
@slhenry Here’s a preview of the functionality, what do you think? https://w3c.github.io/wai-website-components/components/preview/example-home.html

**Comment by yatil** [comment]
@slhenry I made the changes we discussed yesterday. Can you take a look? Thanks!

**Comment by yatil** [comment]
* [ ] Lowercase information

**Comment by slhenry** [comment]
Like it!

**Comment by yatil** [comment]
Reasons for right alignment: 
* Out of the way for most users
* Not essential functionality
* Inline in the responsive/mobile view
* Easy to spot when moving towards the text

**Comment by yatil** [comment]
Published
