### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website#753]
### Resource URL

https://www.w3.org/WAI/tutorials/images/decorative/

### Description

> [Crocus bulbs](https://www.w3.org/WAI/tutorials/images/beyond.html)

gives 404

@remibetin I'm not sure if this is an easy fix or needs more investigation?

### Resource Shortname

wai-tutorials

**Comment by remibetin** [comment]
@shawna-slh This link never worked on live website (see [Web Archive](https://web.archive.org/web/20220801000000*/https://www.w3.org/WAI/tutorials/images/beyond.html))

The same link is used multiple times in https://www.w3.org/WAI/tutorials/images/informative/

After quick investigation, in the Editor’s draft, the link was leading to https://www.w3.org/WAI/EO/Drafts/tutorials/beyond/ when the resource. See https://www.w3.org/WAI/EO/Drafts/tutorials/images/decorative/

I suggest to create a similar "catch-all" page. Not sure "beyond" is the best term (seems a little obscure to me), but I do not have immediate propositions.

**Comment by shawna-slh** [comment]
thanks for the research, @remibetin !

per 16 July 2024 discussion: @remibetin will create a new page. (off-the-top-of-my-head ideas for filename : example-link )

low-medium priority
