### ISSUE TITLE
Icon for Skip to content link misrepresents 

### ISSUE THREAD

**Issue by srinivasuchakravarthula** [w3c/wai-website#8]
Icon before link "Skip to content" appears as representation of a drop down menu and misrepresents. 

![image](https://user-images.githubusercontent.com/5158620/37504396-0bb26980-2904-11e8-9d2a-2602d9a08c92.png)

**Comment by yatil** [comment]
Hi @srinivasuchakravarthula,

We are using + and – for our expand/collapse sections and I don’t think that it is hard to understand, considering the nearby text. A full arrow might look very small in the space.

Thanks for your feedback!

**Comment by srinivasuchakravarthula** [comment]
Do we really need an icon for skip link?




Get Outlook for Android







On Fri, Mar 16, 2018 at 7:38 PM +0530, "Eric Eggert" <notifications@github.com> wrote:












Hi @srinivasuchakravarthula,


We are using + and – for our expand/collapse sections and I don’t think that it is hard to understand, considering the nearby text. A full arrow might look very small in the space.


Thanks for your feedback!

**Comment by carmacleod** [comment]
It looks like a dropdown menu button. I expected that it would contain a menu of skip links. I tried typing space (which is what one uses to open a dropdown menu button) and the I just got the browser's default behavior for scrolling down 1 page.

**Comment by slhenry** [comment]
Thanks for the input. We plan to address it next week.
