### ISSUE TITLE
Speech Recognition page's User Story link is out of date

### ISSUE THREAD

**Issue by ashleemboyer** [w3c/wai-website#815]
In the Learn more section of [the Speech Recognition page](https://www.w3.org/WAI/perspective-videos/voice/), the linked User Story (Alex, reporter with repetitive stress injury) does not exist. It seems maybe the [Ade, reporter with limited use of his arms](https://www.w3.org/WAI/people-use-web/user-stories/story-one/) is the latest page to link to.

**Comment by remibetin** [comment]
Thanks @ashleemboyer: I have fixed the link. For now it points to the archived user story.
