### ISSUE TITLE
Move Participating into About section

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-website#82]
I think we want to
- leave the "Get Involved" link where it is in the header
- leave the page title "Participating in WAI"
- include it in the About left nav (https://w3c.github.io/wai-website/about/) - second item (after "About WAI") with nav_title "Participating"

**Comment by yatil** [comment]
Steps needed: 

- [ ] move content from https://github.com/w3c/wai-get-involved/blob/master/index.md to https://github.com/w3c/wai-about-wai
- [ ] add it as `order: 2` and re-arrange the other entries
- [ ] add `nav_title: Participating`
- [ ] move issues from https://github.com/w3c/wai-get-involved to https://github.com/w3c/wai-about-wai
- [ ] delete/archive https://github.com/w3c/wai-get-involved

**Comment by yatil** [comment]
- [ ] Change links in header and footer
