### ISSUE TITLE
User stories have missing images 

### ISSUE THREAD

**Issue by yatil** [w3c/wai-website#829]
### Resource URL

https://www.w3.org/WAI/people-use-web/user-stories/

### Description

There should be links in there. The additional / after content-images in the URL here causes the image not to show up: 

```
<img src="/WAI/content-images//people-use-web/user-stories/ian.png" alt="">
```

I also fixed the additional unnecessary alternative texts in the following pull request:

- https://github.com/w3c/wai-website/pull/826

**Comment by remibetin** [comment]
Thanks @yatil for raising this issue. I have created a PR to fix this issue: https://github.com/w3c/wai-website-theme/pull/101

**Comment by yatil** [comment]
Thanks, @remibetin – I thought it had to do with the migration to a monorepo. Good catch.

**Comment by remibetin** [comment]
@yatil The fix worked: see https://www.w3.org/WAI/people-use-web/user-stories/
