### ISSUE TITLE
In nav, top align current page indicator

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-website#83]
Instead of:
![pointer-now](https://user-images.githubusercontent.com/6991814/39840964-d86cdea2-53a6-11e8-95d9-d59c5c41f49e.png)

Put it here:
<img width="168" alt="pointer-moved" src="https://user-images.githubusercontent.com/6991814/39840968-dd8d04f2-53a6-11e8-8740-873bbb1df8db.png">

**Comment by yatil** [comment]
Huh, that shouldn’t even be there… (We don’t have it on the other sub-menu levels and the current menu is clearly indicated through other means, so I feel it is redundant.)
