### ISSUE TITLE
Left Navigation: Mismatch between "Spoken Pronunciation" and title of page "Spoken Presentation"

### ISSUE THREAD

**Issue by maryjom** [w3c/wai-website#851]
### Resource URL

https://www.w3.org/WAI/about/groups/task-forces/pronunciation/

### Description

Left navigation calls this TF "Spoken Pronunciation TF" but the title of the page and other related pages say "Spoken Presentation".

### Resource Shortname

wai-groups

**Comment by remibetin** [comment]
Thanks @maryjom: I have updated the left navigation. See https://www.w3.org/WAI/about/groups/task-forces/pronunciation/
