### ISSUE TITLE
Left nav link issue: 404 error on page when using left Nav link to "WAI-Adapt Task Force"

### ISSUE THREAD

**Issue by maryjom** [w3c/wai-website#852]
### Resource URL

https://www.w3.org/WAI/about/groups/task-forces/

### Description

Don't know if the WAI-Adapt TF is still active, but the left navigation on the task forces page has a link "WAI-Adapt Task Force" that yields a 404 broken link when you use it.

### Resource Shortname

wai-groups

**Comment by remibetin** [comment]
Thanks @maryjom: I have fixed the issue with #859 & https://github.com/w3c/wai-website-data/pull/164

See https://www.w3.org/WAI/about/groups/task-forces/adapt/
