### ISSUE TITLE
meta data for cards

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-website#87]
We have it in some of the old resources, but I think they didn't get pulled over...

**Comment by yatil** [comment]
Correct, I have to look into the “Jekyll SEO Tag” plugin, which we have installed but not fully configured: https://github.com/jekyll/jekyll-seo-tag

**Comment by yatil** [comment]
I have enabled Twitter/Facebook cards with default texts. Now need to add specific info to resources in the next step. I’ll add a follow-up issue for the [Third Wave of changes](
https://github.com/w3c/wai-website/milestone/3) (August).
