### ISSUE TITLE
contrast for tables

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-website#89]
from e-mail:

Love the new site design!!

Just some feed back on a contrast issue I came across on the page Referencing and Linking to WAI Guidelines... https://www.w3.org/WAI/standards-guidelines/linking/. The following image shows a visited link with dark purple font on dark blue background within a table row header.
...

Thanks for all your great work!

**Comment by yatil** [comment]
@tasnook Yes, it has not yet been published, but it is fixed in the CSS (which is what we are tracking here :-D) I will pull in a few more changes and publish it to the server tomorrow.
