### ISSUE TITLE
Unable to close mega menus using escape key

### ISSUE THREAD

**Issue by srinivasuchakravarthula** [w3c/wai-website#9]
Menus should be collapsed when user uses escape key. Considering user may accidentally activates menu and if there is no provision to instantly collapse, user may have to navigate through all the navigation items.

**Comment by yatil** [comment]
Hi @srinivasuchakravarthula,

This came up before and I’m working on it :-)

Thanks for the great feedback!

**Comment by yatil** [comment]
Will be addressed with #34.
