### ISSUE TITLE
Link to W3C home page

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-website#93]
Probably W3C logo at top, and W3C in "W3C Web Accessibility Initiative (WAI)" in footer.

(from an unnamed source :-)

**Comment by awkawk** [comment]
I'll out myself as Shawn's unnamed source. I just think that there should be a link from the WAI home page to the W3C _somewhere_...

**Comment by yatil** [comment]
Okay, I will put splitting the logo area up on the roadmap.

**Comment by yatil** [comment]
- [ ] Add to theme

**Comment by yatil** [comment]
Preview here: https://w3c.github.io/wai-website-components/components/preview/example-generic.html

**Comment by slhenry** [comment]
+1 THANKS!

**Comment by awkawk** [comment]
Nice. I'll qualify my next comment with:
1) This is your site, not mine, so do what you like
2) On a 1-10 scale of importance this is probably a -6.

When tabbing it would be better if the focus rectangle for the W3C link didn't overlap the WAI link. It does so ever so slightly, and it is very unlikely to confuse people. It will just make geeky dev/qa people say "why is that doing that?"  

My initial comment is clearly addressed here, whether this additional item is or not. :)

**Comment by yatil** [comment]
@awkawk Good catch, I agree it looks a bit wrong, I’ll see to fix it before deploying it, but I might only get to it later :-)
