### ISSUE TITLE
"Participating in WAI" link is broken

### ISSUE THREAD

**Issue by aljoscha-s** [w3c/wai-website#936]
### Resource URL

https://www.w3.org/WAI/standards-guidelines/harmonization/

### Description

- Click on "Participating in WAI" link in the **Action Steps** section
- Observe that the browser is being redirected to 404 page 

### Resource Shortname

wai-std-harmonization

**Comment by remibetin** [comment]
Thanks @aljoscha-s I have implemented a fix in https://github.com/w3c/wai-website/pull/940. The fix will be published later today.
