### ISSUE TITLE
[fr] Coquille dans le contenu

### ISSUE THREAD

**Issue by baudelotphilippe** [w3c/wai-website#937]
### Resource URL

https://www.w3.org/WAI/fundamentals/accessibility-intro/fr

### Description

Il y a une coquille dans le paragraphe "Contenu de la page" : 
...
- Plus d’nformations

Il manque un i à nformations

### Resource Shortname

wai-accessibility-intro

**Comment by remibetin** [comment]
Thanks @baudelotphilippe: I have implemented the fix in #939. The fix will be published later today.
