### ISSUE TITLE
JavaScript error in classList

### ISSUE THREAD

**Issue by rbtsolis** [w3c/wai-website#94]
when i click on the menu, i see an error
![screen shot 2018-05-26 at 11 08 29 am](https://user-images.githubusercontent.com/8825213/40578683-5cd8ef38-60d5-11e8-96a9-04b3820c3244.png)

I think the error is because sidenav is null:

`var sidenav  = document.querySelector('.sidenav'   );`

**Comment by yatil** [comment]
@rbtsolis Can you tell me in which browser and on which page it happens? Thanks!

**Comment by rbtsolis** [comment]
it is in the home page using Google Chrome Version 66.0.3359.181 (Official Build) (64-bit), exactly in the addClass method

![screen shot 2018-05-28 at 6 30 35 pm](https://user-images.githubusercontent.com/8825213/40632558-87c92e20-62a5-11e8-9cd7-61d4574f697b.png)
![screen shot 2018-05-28 at 6 31 09 pm](https://user-images.githubusercontent.com/8825213/40632559-8dae9230-62a5-11e8-9c85-19b9571dc3d8.png)


If you need an extra hand, just let me know :)
