### ISSUE TITLE
From 'Help improve this page' emails, remove subject

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website#941]
From 'Help improve this page' emails, remove subject

### Resource URL

all resources; component

### Description

e.g., from https://www.w3.org/WAI/fundamentals/ the emails in the 'Help improve this page' include:
```mailto:wai@w3.org?subject=%5Ben%5D%20Accessibility%20Fundamentals%20Overview...```

Please remove that subject.

Rationale: To help with spam processing, we want the subject to be blank by default.

Since we will filter as spam email with blank subject lines, to try to limit legitimate emails with blank subjects, add:

> [include a relevant email Subject]

before
> [put comment here...]

Other suggestions welcome! @iadawn 

### Resource Shortname

na

**Comment by remibetin** [comment]
Hi @shawna-slh,

A PR is ready for review: https://github.com/w3c/wai-website-theme/pull/115

Since it will take time to translate this new text, I have also introduced a `plainText` argument to avoid inserting `<span lang="en"></span>` into the email body.

See the PR description for more info.
