### ISSUE TITLE
User story two content is missing a word

### ISSUE THREAD

**Issue by heybran** [w3c/wai-website#984]
### Resource URL

https://www.w3.org/WAI/people-use-web/user-stories/story-two/

### Description

> However, vague language, metaphors, and implied content in some of the videos makes them to understand.

This paragraph seems to be missing a word after `makes them`, should be `makes them difficult to understand`?

### Resource Shortname

wai-people-use-web

**Comment by remibetin** [comment]
Thanks @heybran.
